### ISSUE TITLE
Adeptus Astartes: Space Wolves missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#100]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Hi The Space Wolves DAta is still not accessible in Barttlescribe. 
I owe the expansion, I can help by sending you pictures if needed. I need those data in BS, pls:-)

**Comment by Mad-Spy** [comment]
Not sure what you mean by "the Space Wolves" data. They are just Adeptus Astartes?
