### ISSUE TITLE
Adeptus Mechanicus: Alpha weapon validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#103]
**File:** Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** For ad mech, the program is incorrectly allowing Ranger and Vanguard Alphas to take their default weapon along with a pistol and melee weapon. They'd supposed to replace their default galvanic rifle or radium carbine if they decide to take a pistol and melee weapon.

**Comment by ohenrik** [comment]
I need help with how to solve this @Mad-Spy or any one else. I’m not sure how to make the limits for this.
