### ISSUE TITLE
Custom DKoK catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#105]
**File:** Astra Militarum.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Hi. My Name on GitHub is "Miru8112". This is NOT a Bug report. I just couldn't figure out how to send a PM in GitHub. Sorry. 
I am currently working on a custm Army file. 
I took the Astra Militarum Files and compared all the legal options to the Death Korps of Krieg data in Imperial Armour. 
I made connections between the weapon -, Order - and Unit Choices (Cost and role) and currently use this to use my DKoK Army as a semi-legal Kill Team Army. 

What I want to ask: Is there a way I can submit those data to you so you can incorporate something like a "experimentel" tab where, when checked, custom Armies pop up? Or do you have no interest in this? 

In case you are not: 
You being the Pro, can I make such a file myself and upload it to my personal BattleScribe? So I can us my profiles in the list builder? 

If you are interested, you can reach me via ~~*personal email deleted*~~

**Comment by amis92** [comment]
@miru8112 you can post an issue here personally, and issue in general is the correct place to discuss things. GitHub doesn't offer PMs. For a more chatty service, please visit our Gitter room (GitHub authorization is supported).

As for the custom armies, no, we do not support them. For all the other questions, I'd advise reaching to gitter. :)
