### ISSUE TITLE
Tyranids: Barbed Strangler cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#112]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The point value for the barbed strangler in Tyranids is off. It is listed as 1 pt rather than 3

**Comment by amis92** [comment]
Solved already, #107
