### ISSUE TITLE
Grey Knights: Falchions Unclear?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#118]
**File:** Grey Knights.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Grey knights falchion points are shown as 2 instead of 1 as they should be

**Comment by GenWilhelm** [comment]
Falchions are listed as 1 point *per weapon*, and the only way to take them is as a pair. So you're actually purchasing two falchions at 1pt each, for a total of 2pts.

Perhaps it could be clearer that you're purchasing two weapons?
