### ISSUE TITLE
Genestealer Cults: Metamorph Claw Validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#124]
**File:** Genestealer Cults.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** For Kill Team: Genestealer Cult: Hybrid Metamorph: Leader:
  The selections of:
    " This model may do one of the following: 
        "Replace its Metamorph talon and rending claw with a Metamorph claw"
    "A Metamorph Leader may take a Bonesword" 
results in a Roster Error: "Metamorph Leader must have one more selections from Melee Weapons (maximum 2)"

 Boneswords are clearly Melee Weapons as indeed are Metamorph claws....the "Edit" function indicates that the Bonesword is mistakenly present in the 'general's wargear section.

Kudos for your attention afore and thereafter,
Cheers, Sir

**Comment by GenWilhelm** [comment]
This is why I shouldn't try to fix things after midnight >_>
