### ISSUE TITLE
Grey Knights: Modify range of GK Psybolt due to Rites of Banishment?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#131]
**File:** Grey Knights.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The range and description for psybolt for Grey knight is incorrect. BattleScribe states that the range for psybolt is 18". But on the Grey knights datacard there is a rule that says:" rites of banishment: when this model manifests the Psybolt psychic power it has a range of 12" if psybolt is successfully manifested, and the target model is a daemon, the target suffers D3 mortal wounds, even if the result of the psychic test was not 11+."

**Comment by Mad-Spy** [comment]
This is not incorrect. The range of the Psybolt power _is_ 18", as per p26 of the Core Manual.

The Grey Knights just happen to have an ability which overrides this.

I leave it up to the GK owner to decide whether to override the default range on Psybolt's profile.

**Comment by tekton** [comment]
I'm playing a few games this week, I'll see how both sides go for referencing things.

**Comment by tekton** [comment]
I have three options I'm working on, got busy with work and weather issues- will get back to it "soon"™
