### ISSUE TITLE
Model count validation

### ISSUE THREAD

**Issue by Pukwudji** [BSData/wh40k-killteam#145]
When creating a kill team with only 3 members, I get a validation error, it seems not to be counting the leader, similarly I can create a kill team with 22 members before getting the validation error for having too many models

**Comment by GenWilhelm** [comment]
Which faction/catalogue are you using?

**Comment by Pukwudji** [comment]
Sorry forgot to say Grey Knights, will try and replicate in others

**Comment by Pukwudji** [comment]
Tried a few others seems to be just Grey Knights

**Comment by GenWilhelm** [comment]
Thanks!

Yeah, it looks like the Justicar isn't correctly marked, so he isn't being counted.
