### ISSUE TITLE
T'au - DS8 Tactical Support Turret not a Root Selection Entry

### ISSUE THREAD

**Issue by s4dfish** [BSData/wh40k-killteam#156]
DS8 Tactical Support Turret is not currently able to be selected and added to a Kill Team.  I suggest adding a Selection Entry to the Root Selection visible when there's a Fire Warrior Shas'ui or Fire Warrior Breacher Shas'ui.

**Comment by Mad-Spy** [comment]
You add a DS8 by adding it to an eligible Shas'la. There is a checkbox to add one when you add such a Shas'la to your kill team.

![image](https://user-images.githubusercontent.com/29306451/46405350-ea05aa00-c6ff-11e8-9480-daaa46199bf2.png)
