### ISSUE TITLE
Necron Non-specialists are not fire teams in campaign

### ISSUE THREAD

**Issue by DaeronAlagos** [BSData/wh40k-killteam#157]
When creating a Campaign Command Roster for Necrons, the Non-specialists are not Fire Teams but normal members (ie a standard Kill Team). This can be replicated by creating a new roster, change the List Configuration to 'Campaign: Command Roster' and adding a non-specialist. The usual option of adding fire team members on the right doesn't appear.

**Comment by Kohato** [comment]
Closed via 3617a66
