### ISSUE TITLE
Elucidian Starstriders: Sanastasia Minst is not under Elites

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#159]
**File:** Elucidian Starstriders.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Sanistasia Minst is not under ELITES and therefore will not validate

**Comment by OftKilted** [comment]
There is no “Elites” in Killteam? This appears to be invalid for the Killteam catalog. (May be valid for the 40k Catalog.)

**Comment by Mad-Spy** [comment]
She is definitely under Elites in the 40k catalogue
![image](https://user-images.githubusercontent.com/29306451/46458277-2ba05e80-c7ad-11e8-9e2e-2b250b51516d.png)

but as @OftKilted said, there are no Elites in Kill Team.
