### ISSUE TITLE
Necrons: No Fire Teams in catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#160]
**File:** Necrons.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When using the campaign rost, the fire teams can’t be selected, only a single model can. Looking at the other army’s i can choose fire teams.

**Comment by Mad-Spy** [comment]
This is fixed in the next release.
