### ISSUE TITLE
Adeptus Astartes

### ISSUE THREAD

**Issue by JohnnyKryptonite** [BSData/wh40k-killteam#162]
FAQ changes- missing all FAQ changes, i.e. these: 

First- THANK YOU! 

Page 85 – Intercessor, Wargear Options
Add the following option:
‘• One Intercessor, Intercessor Gunner or Intercessor
Sergeant in your kill team may take an auspex.’

Page 84 – Tactical Marine, Specialists
Add ‘Medic’.

Page 85 – Intercessor, Wargear Options
Add the following option:
‘• One Intercessor, Intercessor Gunner or Intercessor
Sergeant in your kill team may take an auspex.’

Page 85 – Intercessor, Abilities
Add the following ability:
‘Auspex: At the start of the Shooting phase, you can
choose another Adeptus Astartes model within 3" of
a friendly model equipped with an auspex that is not
shaken. That model does not suffer penalties to their hit
or Injury rolls due to their target being obscured.’

Page 85 – Intercessor, Abilities, Auxiliary
Grenade Launcher
Add the following sentence:
‘This model’s Grenade weapons are affected by the long
range rule.’

Page 85 – Intercessor, Specialists
Add ‘Medic’.

**Comment by FarseerVeraenthis** [comment]
What file version are you using??
This might be a case of "please update your data" ,because I'm fairly sure @Mad-Spy covered these changes and released them already :smile:

**Comment by Mad-Spy** [comment]
Yes, these were all done in v1,1.

**Comment by Mad-Spy** [comment]
No worries. We've all had problems with BS not pulling updates on occasion. I tend to just remove the data set and reload the whole thing.
