### ISSUE TITLE
Orks: Incorrect Strength for Big shoota

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#165]
**File:** Orks.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The stat line for the Big Shoota incorrectly shows a Strength value of 5 as opposed to the strength value of 4 shown in the Kill Team rulebook. I noticed a similar error with Space Marine Bolt Rifles (already fixed) that this error is consistent with.

**Comment by Mad-Spy** [comment]
Are you sure you mean the Big Shoota? It has Strength 5 in the rulebook.
