### ISSUE TITLE
Adeptus Mechanicus: Commanders Expansion

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-killteam#171]
__Ad Mech__

- [x] Enginseer
- [x] Tech-priest Dominus

**Comment by stormclac** [comment]
Heya, how do I select commanders in BattleScribe?

**Comment by Mad-Spy** [comment]
You'll either need to clone the repo, and download the Commanders branch, if you have Windows, or wait until we release them in the next couple of days.
