### ISSUE TITLE
Asuryani: Commanders Expansion

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-killteam#172]
__Asuryani__

- [x] Farseer
- [x] Warlock
- [x] Autarch

- [x] Runes of Battle
- [x] Runes of Fate

**Comment by Mad-Spy** [comment]
Autarch should get JUMP PACK and FLY when he takes Wings.

**Comment by Mad-Spy** [comment]
It's the Generalist restrictions in the GST that need sorting.

**Comment by FarseerVeraenthis** [comment]
That's where they are! Righto, cheers for the pointer :smile:

**Comment by FarseerVeraenthis** [comment]
should be done, at least for now :smile:
