### ISSUE TITLE
Drukhari: Commanders Expansion

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-killteam#173]
__Drukhari__

- [x] Archon
- [x] Succubus
- [x] Haemonculus

**Comment by FarseerVeraenthis** [comment]
closed by https://github.com/BSData/wh40k-killteam/commit/fe2a753138b2714891bad0b8453cc22ba72abb42 I think...

**Comment by Mad-Spy** [comment]
- Succubus has no base cost
- Succubus Lightning Dodge shouldn't be restricted to the Fight phase.
- Succubus No Escape wording does not match rule book.
- Agoniser special ability doesn't match rule book.

- Archon should be able to select Agoniser.
- Archon should have default splinter pistol.

- Haemonculus has no Specialism SSEG link.

- Typo in Power from Pain level 5 "enemey".
