### ISSUE TITLE
Drukhari: Command Roster

### ISSUE THREAD

**Issue by xiontawa** [BSData/wh40k-killteam#185]
When making a Drukhari Command Roster, it puts out errors for all non-specialist selections, and doesn't list the appropriate models for Fire Teams.

![capture](https://user-images.githubusercontent.com/3139771/47239865-7aa4e100-d3b4-11e8-933f-f86f5810a57f.PNG)
This is Matched Play: Command Roster. All of those selections are the only options for non-specialists. pg144

![capture2](https://user-images.githubusercontent.com/3139771/47239866-7b3d7780-d3b4-11e8-9bc2-022a68319eb4.PNG)
This is Campaign: Command Roster. Gunners and Fighters can be a Fire Team. pg144

**Comment by Mad-Spy** [comment]
I'm unable to replicate this issue immediately v1.1.1. If I select a Matched Play Roster, I can add Non-specialists with no errors.

If I create a Campaign Roster, I can add a Fire Team, and add models to it without error.

Note that you cannot switch between the modes without errors. Is this what you are trying to do? Battlescribe cannot support moving the Non-specialists into Fire Teams.

**Comment by xiontawa** [comment]
Okay, the first issue fixed itself making a new roster from scratch. But the 2nd issue remains on the new rosters. I've replicated it on Android, iOS, and windows. I'm thinking it's just a lack of data, as gunners and fighters can be in a fire team, but just aren't showing.

**Comment by Mad-Spy** [comment]
Right, so you do have the right data. You need to add a Fire Team to your Roster first, and then add members to it. The two Fire Teams you are seeing are a selection option.
.

**Comment by xiontawa** [comment]
Ohhhhhh. Well, I feel stupid now...

Thanks for clearing that up. Sorry for bothering you.

**Comment by Mad-Spy** [comment]
No worries.
