### ISSUE TITLE
Rules vs. Abilities

### ISSUE THREAD

**Issue by xiontawa** [BSData/wh40k-killteam#186]
(I hope I'm not intruding by using this to post "comments" about the data files, and if I am, just let me know and I'll find another way to report my findings and thoughts.)

I've noticed some Kill Teams have their Abilities under the "Rule" category, and some have them under the "Ability" category. I'm not sure why there is a difference depending on the KT, but one comment I'd like to make is: I think the abilities of the models (not the specialisms/etc) looks a lot better under the "Rules" catalog, and my lists I've made with the KTs that have it like that look way cleaner.

For reference, the KTs I'm speaking about with the non-clean look is AA and GK, and the one I noticed the lot cleaner output is Drukhari.

Now, if there is a reason for this not being done like the Drukhari on some others, that's cool, but I just really think the lists look a LOT cleaner when it's like that. :)

**Comment by Mad-Spy** [comment]
We'll discuss this after we've got the Commanders expansion work done.

**Comment by Mad-Spy** [comment]
We're leaving this to developer preference.
