### ISSUE TITLE
Deathwatch: Validation error when adding "Gunners"

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#188]
**File:** Deathwatch.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I get an error message for my Deathwatch Kill Team stating that maximum number of gunners is 1, when the rulebooks states I can have up to four and in neither the FAQ or Errata was this changed

**Comment by OftKilted** [comment]
Unable to replicate error using current data set.

**Comment by Mad-Spy** [comment]
Can you please provide some additional details on the exact error message you are receiving and the list you have created? Then we'll try and replicate it.

**Comment by Mad-Spy** [comment]
Without further details we cannot investigate this any further. Closing ticket.
