### ISSUE TITLE
Warhammer 40,000 Kill Team: Difficulties adding units to rosters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#189]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I can’t get it to allow me to add units to a roster. It sounds odd, but I haven’t found a way to do it yet. I feel I’ve tried every button and combination thereof by now. If there is a way for iPhone, I think you should redesign it to be more obvious. I haven’t even found a list of units yet. I’ve been trying Mechanicus now.

**Comment by xiontawa** [comment]
This is not a bug, nor is it a problem with this specific GST. I believe you are not aware on how to use Battlescribe itself.

My first question to you is, have you used Battlescribe before?
My second would be, have you loaded the Kill Team Data files?

Finally, the design of the app has nothing to do with the people here. This is the repository for the Kill Team specific data files. If you have an issue with the app itself, you need to notify the author.

**Comment by Mad-Spy** [comment]
This video is a little old, but shows the basics of how to get the data files on your device and use them to create rosters. https://www.youtube.com/watch?v=LSsFH7hv3Tg. It should still be mostly relevant as the basic layout of the app hasn't changed too much.

Try that, and come back if you still have questions.
