### ISSUE TITLE
Harlequins: Fire Team Advances add 2 points rather than 1

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#191]
**File:** Harlequins.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** For player fire teams selecting advances increases model point cost by 2 points per advance instead of 1 point.

**Comment by Mad-Spy** [comment]
The increment has been added to both the base "Player" SSE and the link in the Fire Team, so it's incrementing twice.
