### ISSUE TITLE
????: Fire Team Advances add 2 pts instead of 1.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#192]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** When adding a Fire Team to a Campaign roster, after choosing to advance the fire team, it adds +2 to the cost of each model, instead of the +1 that should be assigned for each level gained by a Fire Team.

**Comment by Mad-Spy** [comment]
If this is on the Harlequins catalogue, then this is a duplicate of #191 and will be fixed in the next release.

**Comment by Mad-Spy** [comment]
As there has been no update on this ticket, I am assuming it's the Harlies issue and closing it.
