### ISSUE TITLE
Astra Militarum: Tempestor Prime cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#198]
**File:** Astra Militarum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** Tempestor prime pricing is off, it's currently set to 45 for lvl 1, 50 for lvl 2, 65 for lvl 3 and 4. It should be 25, 30, 45, 65 respectively.

**Comment by Mad-Spy** [comment]
There doesn't seem to be any problem with the pricing on the released version. Please ensure you've downloaded v1.2.0 of the Kill Team release, with Astra Militarum v10.
