### ISSUE TITLE
GST: Tactical Planner Trait cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#205]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The "Tactical Planner" commander trait cost 20 points in te app but it actually costs 15 points (Page 16 of the Kill Team Commanders Rulebook)

**Comment by Mad-Spy** [comment]
Duplicate of #199
