### ISSUE TITLE
T'au Empire: Typo in Saviour Protocols

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#208]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Please correct the "whan" to a "when"

Saviour Protocols: If a DRONE is within 3" of a friendly T'AU EMPIRE INFANTRY model whan an ...

should be:

Saviour Protocols: If a DRONE is within 3" of a friendly T'AU EMPIRE INFANTRY model when an ...

**Comment by amis92** [comment]
@Mad-Spy thanks!
