### ISSUE TITLE
Orks - Shokk attack gun validation on Big Mek

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#210]
**File:** Orks.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** When choosing a Shokk Attack Gun for an Ork Big Mek, you get the error message: Big Mek has 1 too many selections of Shokk Attack Gun (maximum 0)

**Comment by Mad-Spy** [comment]
You only get this message if you attempt to take both a KFF and a Shokk Attack Gun, which is not possible.

The Big Mek can either swap its gun, OR it can take a KFF, not both, as per its datasheet.
