### ISSUE TITLE
Orks: Nobs can be added above their limit in Battle-forged teams

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#216]
**File:** Orks.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** In building a Campaign: kill team, under kommando fire team i can take more that one kommando boss nob. Same applies for boss nobs in boyz fire team.
I already have both as specalist in this instance. 
Keep up the good work, many thanks

**Comment by Mad-Spy** [comment]
Fixed in v16.
