### ISSUE TITLE
Kroot Kill Team

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k-killteam#217]
Tracker for new Kroot kill team rules.

**Comment by penguin20000** [comment]
I've made a new branch for the Kroot cat. I still need to make the changes for the campaign type stuff, kill teams etc. But everything should be there for matched, open play etc

**Comment by Mad-Spy** [comment]
- Krootox Rider's Kroot gun is missing it's Strength.
- Dahyak Grekh needs to be added as a Commander.

**Comment by Mad-Spy** [comment]
Something odd is going on with Dahyak's lvl4 options. If I choose "Climber" for lvl2, Skulker isn't an option for lvl 4, and if I select "Skulker" for lvl2, it doesn't get removed as a lvl4 option.

Also, I saw a mention online that said you can take Carnivores in a T'au KT? If that's true, they'll need adding in to that cat.

**Comment by penguin20000** [comment]
- [x] Fix Dahyak's lvl4 options
- [x] Add Carnivores to T'au Empire
- [x] Add default members to fireteams.
