### ISSUE TITLE
[Anon] Bug report: Gellerpox Infected.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#222]
**File:** Gellerpox Infected.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Please update gellarpox to support multilevel commanders and traits like they did with all the main factions, poor vulgrar has it hard enough :(

**Comment by Mad-Spy** [comment]
Gellerpox and Starstriders have supported higher level Commanders since they were introduced, before the Commanders book even came out.
