### ISSUE TITLE
Asuryani - Max Gunner Limit not validating properly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#224]
**File:** Asuryani.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** You can select more then 2 guardian gunners, taking 1 as leader, 2 as specialista and 2 as non-specialists, but in rulebook there are max 2 gunners in kill team

**Comment by Mad-Spy** [comment]
Looks like it's validating within a type (Specialists, Non-specialists) but not across the whole roster.
