### ISSUE TITLE
Drukhari - Cabalite Gunner Validation Problems

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#225]
**File:** Drukhari.catz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** You are only able to add One Kabalite Gunner to your killteam despite the core manual reading "Up to two Kabalite Warriors in your kill team can be Kabalite Gunners"

**Comment by Mad-Spy** [comment]
I can't replicate this one. I can add two before I get a validation error.
