### ISSUE TITLE
Drukhari - Wych Validation Problems

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#226]
**File:** Drukhari.catz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** You are only able to take One Wych as a Wych fighter despite the core manual reading "Up to three Wyches in your kill team can be Wych Fighters"

**Comment by Mad-Spy** [comment]
Can't replicate this one either. No validation error appears until you have over 3 fighters in a list.
