### ISSUE TITLE
Genestealer Cults: Add Kelermorph

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#227]
**File:** Genestealer Cults.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** Add kelermorph pls, would like to see how he works in a team

**Comment by Mad-Spy** [comment]
This will be added when we can find a copy of the datasheet and points costs.

**Comment by mcbanks** [comment]
I have the box and could provide the sheet. Would this help or just stat line?

**Comment by Mad-Spy** [comment]
I can't ask you to upload an image of the datasheet and points values, but I have no control over what you might do.

**Comment by mcbanks** [comment]
name="Kelermorph" 
name="M"	value="6"
name="WS"	value="3+"
name="BS"	value="2+"
name="S"	value="3"
name="T"	value="3"
name="W"	value="4"
name="A"	value="3"
name="Ld"	value="8"
name="Sv"	value="5+"
name="Max"	1

This model is armed with 3 liberator autostubs and a cultist knife

name "Liberator autostub"
<characteristic name="Range" value="12&quot;"
<characteristic name="Type" value="Pistol 1"/>
<characteristic name="S" value="4"/>
<characteristic name="AP" value="-1"/>
<characteristic name="D" value="2"/>
<characteristic name="Abilities"  value="-"/>

name "Cultist knife"
<characteristic name="Range" value="Melee"
<characteristic name="Type" value="Melee"/>
<characteristic name="S" value="User"/>
<characteristic name="AP" value="0"/>
<characteristic name="D" value="1"/>
<characteristic name="Abilities"  value="Each time the bearer fights, it can make 1 additional attack with the weapon"/>

Abilities

Cult Ambush: After deployment but before the first battle round, roll a D6 for this model. On a 5+ this model can immediately move up to 6".

Inspirational Deeds: If any enemy model is taken out of action by an attack made with this model's liberator autostubs, then until the end of the phase, re-roll hit rolls of 1 for models from your kill team wilst they are within 6" of this model.

Lightning Reflexes: This model has a 5+ invulnerable save.

Specialists: Fortitude, Leadership, Stealth, Shooting

Faction Keyword: Genestealer Cults

Keywords: Tyranids, Infantry, Commander, Kelermorph

Model points: level 1= 25 2=30 3=45 4=65 points
Liberator autostub= 0 points
