### ISSUE TITLE
AdMech - Commander - TP Manipulus

### ISSUE THREAD

**Issue by DoBene29** [BSData/wh40k-killteam#228]
Can you add the Tech-Priest Manipulus to the Adeptus Mechanicus Killteam?

Thank you so much in advance, you guys rock!!

**Comment by Mad-Spy** [comment]
Unfortunately, we don't currently have access to the datasheet, so we can't add this model. When/if we can find a copy, we'll add it.

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/52555798-a411ce80-2de2-11e9-9be3-322c24bc6c41.png)

![image](https://user-images.githubusercontent.com/29306451/52555808-aa07af80-2de2-11e9-9d47-d6363e946237.png)

**Comment by DoBene29** [comment]
Perfect that you guys have the datasheet now, can't wait for the update :)
