### ISSUE TITLE
Astra Militarum: Add Severina Raine

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#231]
**File:** Astra Militarum.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** https://spikeybits.com/wp-content/uploads/2019/02/kill-team-severina.jpg Severina Raine 20p

**Comment by Ozsie** [comment]
I have added a Pull Request to add Severina Raine, #240
