### ISSUE TITLE
[Anon] Bug report: Harlequins.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#232]
**File:** Harlequins.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** Death jester has his abilities show up at the bottom under Selection Rules

**Comment by Mad-Spy** [comment]
The choice to display Abilities either as a profile-type entry or a rule-type entry is up to the individual catalogue developer.
