### ISSUE TITLE
Astra Militarum: Problem with getting special weapon Guardsmen?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#244]
**File:** Astra Militarum.catz

**BattleScribe version:** 1.02.08

**Platform:** Android

**Dropbox:** No

**Description:** It won't allow me to have more special weapon guards men even though I have more than 1 squad

**Comment by Mad-Spy** [comment]
Models aren't organised into squads in kill team, so I'm afraid I don't understand the problem you're having. Could you provide a screenshot or at least some more details?

**Comment by Mad-Spy** [comment]
Closing due to lack of info.
