### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by immortaldevs** [BSData/wh40k-killteam#247]
I'm looking to join as a collaborator so that I can help with the upcoming Kill Team: Elites data. Specifically, I can get the Tau stuff added before the release on Saturday.

**Comment by Mad-Spy** [comment]
Hi, just jump onto the Discord, https://discord.gg/UrrPB3T and find us in #killteam-data. I saw you made a fork, so just get your stuff done and then send a pull request for review.
