### ISSUE TITLE
Grey Knights: Terminator weapon options incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#254]
**File:** Grey Knights.catz

**BattleScribe version:** 2.02.02

**Platform:** Android

**Dropbox:** No

**Description:** "A Terminator Gunner may replace their storm bolter with an inceniator, psilencer or psycannon". Now there is no opportunity to do so. I can only change melee weapon.

**Comment by Mad-Spy** [comment]
Duplicate of #255
