### ISSUE TITLE
Adeptus Astartes: Sternguard Sgt wargear issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#258]
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Sternguard Sergeants have the wrong wargear available

**Comment by Mad-Spy** [comment]
Please elaborate as to what the actual problem is. Vague reports are very unhelpful.

**Comment by Mad-Spy** [comment]
Found the errors myself and fixed them.
