### ISSUE TITLE
Deathwatch.cat - Intercessor

### ISSUE THREAD

**Issue by warcode** [BSData/wh40k-killteam#26]
Primaris units taken need to pay for all weapons according to the Deathwatch ranged weapon list.

An Intercessor has a bolt rifle (2pt) and a bolt pistol(2pt) bringing the cost up to 19, not 17.

**Comment by FarseerVeraenthis** [comment]
an Intercessor is 15 points... 15+2 = 17...
Unless I'm looking at the wrong leaked screengrab...

**Comment by warcode** [comment]
https://i.imgur.com/r9Laqi6.png

"...it must pay the point value for its ranged weapons."

It is 15 points, but is with both a bolt rifle and a bolt pistol. Both of these are 2 points in the Deathwatch ranged weapon list. https://i.imgur.com/IFE3y7v.png

**Comment by Mad-Spy** [comment]
What you all seem to have missed is that I had completely forgotten to give the Intercessors a bolt pistol in the first place!

**Comment by Mad-Spy** [comment]
And also fixed in Adeptus Astartes on the SM-DW branch.
