### ISSUE TITLE
Adeptus Astartes: Suppressor unit type missing

### ISSUE THREAD

**Issue by cecil0610** [BSData/wh40k-killteam#265]
Noticed Suppressor is missing from the unit types list, in 2.02.03 iOS

**Comment by Mad-Spy** [comment]
Fixed in v1.3.1.

**Comment by cecil0610** [comment]
> Fixed in v1.3.1.

Cool thanks. I'll wait for v1.3.1 :D
When I refreshed my data this morning, I got v1.3.0 somehow.
Refreshed again it's still v1.30 currently.

**Comment by Mad-Spy** [comment]
I only released it about 90 minutes ago. It'll be available soon.
