### ISSUE TITLE
CSM Gunners

### ISSUE THREAD

**Issue by vicanic** [BSData/wh40k-killteam#27]
Not displaying DttFE or Transhuman Phys on CSM Gunners

**Comment by vicanic** [comment]
CSM Gunners still dont have Transhuman Physiology

**Comment by Mad-Spy** [comment]
Are you looking at the current release or are updating from the repo?

**Comment by vicanic** [comment]
I am downloading it from here to my dropbox. Just tested again. DttFE is displaying, but Transhuman still isnt. Just tested it again
