### ISSUE TITLE
Space Marines: Sternguard Vet should always have access to plasma cannon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#283]
**File:** Space Marines.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** Yes

**Description:** Adeptus Astartes Sternguard gunners should be able to select plasma cannon from the heavy weapons list for 12pts.
Adeptus Astartes Terminator Gunners that take a cyclone missile launcher and storm bolter should also make the power fist optional as cyclone missile launcher used to replace the power fist with a targeter arm, but that is no longer mandatory.

**Comment by Mad-Spy** [comment]
1. They can if you choose Dark Angels as your Chapter Tactic, otherwise it's not a valid choice.
2. It is not optional according to the datasheet, so it is not optional in the data.

**Comment by RoguePlank** [comment]
Your response for 1. is incorrect. The plasma cannon is only Dark Angels chapter exclusive weaponry on Terminator Gunners (page 39 of the Elites book).
A Veteran Sternguard Gunner (Page 40) from any chapter can select the plasma cannon from the heavy weapons list (Page 42).

**Comment by Mad-Spy** [comment]
Yes, you're right! Misread that one. I'll sort it out.

**Comment by RoguePlank** [comment]
Appreciated!
