### ISSUE TITLE
Adeptus Astartes: Lightning claw cost oddness

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#285]
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** Yes

**Description:** Adeptus Astartes vanguard veteran selecting 2 lightning claws shows 2pts in the weapon list, when it should say 3pts (1pt for 1, 3pts for 2). However the model total points is correct, adding 3 points to the total when 2 claws are selected.

**Comment by Mad-Spy** [comment]
Thus was due to a bug in the BS editor which prevented me from putting decimals into costs (setting then both to 1.5 pointd). Therefore, I separately incremented the model cost to get around it.
I think it's been fixed now, but I'm waiting for my version to update.
