### ISSUE TITLE
Astartes Vanguard Veteran Krak grenade profile

### ISSUE THREAD

**Issue by RoguePlank** [BSData/wh40k-killteam#294]
Space marines vanguard veteran krak grenade profile is showing as 1 damage. Should be D3 damage, same as other astartes krak grenade profile. 

Both frag and krak grenade(s) profiles appear to have been duplicated as they show up with multiple entries in the weapons list for the same weapon, though one is plural.

**Comment by Mad-Spy** [comment]
There's some further work I need to do following the move to using a Library file for those elements which are shared between Adeptus Astartes and Deathwatch. This is an artefact of that. I've sorted it for now.

**Comment by RoguePlank** [comment]
sounds like witchcraft....
