### ISSUE TITLE
Grey Knights Librarian number of psychic powers.

### ISSUE THREAD

**Issue by RoguePlank** [BSData/wh40k-killteam#312]
The Grey Knights Commander - Librarian in terminator armour should only be able to select 3 psychic powers. He can currently select all of them.
He knows Psybolt (Rites of Banishment) by default and 2 powers from the Sanctic discipline on page 46 of Elites. However, page 17 of the Commanders book states that any Commander Psyker may trade their psybolt ability or any other ability they know for any of the psychic powers listed on page 17 of commanders.
In any case, it still works out as a maximum of 3 powers selectable. This restriction should also apply to the adeptus astartes commander librarians, though theirs will be chosen from the librarius discipline rather than the sanctic discipline.

**Comment by Mad-Spy** [comment]
Oops, some idiot forgot to add max 3 constraints to the entries.
