### ISSUE TITLE
Chainfists, terminator captains and spacewolves 

### ISSUE THREAD

**Issue by RoguePlank** [BSData/wh40k-killteam#317]
1. The chainfist being space wolves exclusive on page 42 of Elites is intended to mean that only space wolves may replace their storm bolter arm with a second melee weapon as written in the 2nd spacewolves point on page 39, some of those melee weapons are exclusive to spacewolves, but the chain fist is not one of them. Its only Spacewolf exclusive to take 2 chainfists on one model. 

1. Spacewolf terminators, gunners and sergeants should also be able to swap their storm bolter for any of the combi weapons also listed on page 39.

1. In a related issue, the captain in terminator armour commander should be able to select the chainfist as its specifically listed in his entry on page 37.

**Comment by RoguePlank** [comment]
It could be argued that chainfist (space wolves only) is a typo, but as I've explained that's not entirely true, it's just very misleading. Space wolf terminators just have much greater freedom to select weapons than normal terminators.

**Comment by Mad-Spy** [comment]
1. Yes, you're right. Not sure why I restricted it to one for Wolves.
2. They already can?
3. Yes; this was broken, one of the modifiers wasn't triggered like I expected.

**Comment by RoguePlank** [comment]
2. Ahaaa, I didn't spot the separate SW terminator units, very clever. I was just selecting ultramarine terminators then swapping the chapter tactics to spacewolves. Didn't notice the error flags for incorrect unit selections. Nicely done.

Took a couple hours back and forth arguing on facebook to get my head around these rules, glad to see you've already got the same understanding as me! Excellent work.
