### ISSUE TITLE
Adeptus Astartes: Can't create rosters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#321]
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** I keep trying to access addptus astartes on my  zte blade a330 phone but I can't it Is on Android 7.1.2
It sometimes just keeps loading so I cleared all my files 
Sometimes it will go back to to preparing data
Then others it will say to go to low ram mode but it doesn't change anything
Ive seen multiple people have this problem on different devices 
It works perfectly fine on desktop

**Comment by Mad-Spy** [comment]
This is not a data issue (as evidenced by the fact that it works on desktop). Please raise an issue with the app developer.
