### ISSUE TITLE
Repository has disappeared from the appspot battlescribe downloads list.

### ISSUE THREAD

**Issue by RoguePlank** [BSData/wh40k-killteam#326]
As per title, the android app was unable to refresh the killteam data, so I manually went to point the app to the repository location and it's not there anymore on appspot. Is this normal part of the update process, as I see an update for the killteam data was released a couple days ago?

**Comment by Mad-Spy** [comment]
Not a data issue. Appspot regularly gives up and loses the repos. It'll be back eventually.

**Comment by hanahanabi** [comment]
Is there a way to be notified when it's back? I was having a devil of a time trying to figure out what j was doing wrong

**Comment by hanahanabi** [comment]
Whelp. It seems to be back!

**Comment by amis92** [comment]
https://github.com/BSData/bsdata/issues/208 - it's being slowly worked on.
