### ISSUE TITLE
[Anon] Bug report: Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#329]
**File:** Adeptus Custodes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** I cant open the rooster. Downloading and dont go to modify the members un the kill team, just back to the "all rooster" page

**Comment by Mad-Spy** [comment]
This doesn't sound like a data issue. Please report it to the app developer.
