### ISSUE TITLE
[Anon] Bug report: Adeptus Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#335]
**File:** Adeptus Custodes.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When viewing the Adeptus Custodes Shield-Captain, his entry does not include his model abilities (Aegis of the Emperor, Superior Transhuman Physiology), or those that come from his selected Commander specialism.

**Comment by r0tational** [comment]
Oh, and to be clear, wargear abilities do appear!

**Comment by Mad-Spy** [comment]
Can't replicate the missing Specialism abilities; they show up for me. However, the Shield-Captain and Allarus were both missing Aegis and STP, so I've added them back in. Fixed in v4 of Custodes.
