### ISSUE TITLE
Drukhari Acothyst

### ISSUE THREAD

**Issue by Blank05** [BSData/wh40k-killteam#345]
The Acothyst doesn't appear, when you view your list, in the profile summary section and there is another Wrack on the list. When there are no other Wracks, the Acothyst appears as a Wrack with the Acothyst statline.
![Screenshot_20190619-105446](https://user-images.githubusercontent.com/48073348/59776393-ba440580-9280-11e9-8248-507d9f8144ba.jpg)
![Screenshot_20190619-105429](https://user-images.githubusercontent.com/48073348/59776404-bfa15000-9280-11e9-934d-63ec3cbc5926.jpg)

**Comment by Mad-Spy** [comment]
Oops. Forgot to rename the profile after pasting it from a standard Wrack. Fixed in v15 of the Drukhari file.
