### ISSUE TITLE
Adeptus Astartes: Veteran Sgt missing Auspex

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#350]
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Veteran Sargent Space Marine: Missing Auspex as/replacing melee weapon.

**Comment by Mad-Spy** [comment]
Only a Sternguard Sergeant can take an Auspex, not a standard Veteran Sgt.
