### ISSUE TITLE
Warhammer 40k Kill Team repo deleted from BattleScribe repo

### ISSUE THREAD

**Issue by alerickson0** [BSData/wh40k-killteam#351]
Greetings,

First of all, apologies if this is not the correct place to open this issue.

So, I recently updated my BattleScribe to version 2.02.04.125. And when I attempted to update my data for Warhammer 40k Kill Team, I receive the following error:

Failed to download from one or more repositories

1) net.battlescribe.model.config.Repository@40e3ca00: https://battlescribedata.appspot.com/repos/wh40k-killteam

2) https://battlescribedata.appspot.com/repos/wh40k-killteam/index.bsi: https://battlescribedata.appspot.com/repos/wh40k-killteam/index.bsi

Also, note I deleted my data first before I attempted to update my Kill Team data. Next tried to see if the repos existed at the step 2) URL:

https://battlescribedata.appspot.com/repos/wh40k-killteam/index.bsi

Unfortunately, it did not.

**Comment by Mad-Spy** [comment]
Yes, sometimes AppSpot drops repos. It'll come back at some point. We never know when.

**Comment by alerickson0** [comment]
Alright, good to know for next time.

Thanks,

Alvaro
