### ISSUE TITLE
T'au Empire: Various issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#36]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Fire Warriors, Pathfinders and Breachers may take the MEDIC specialization; while XV25s cannot take this specialization.
All Breachers come stock with a pulse pistol that cannot be unequipped with the option to take a pulse blaster. Breachers may use the pistol, the blaster or both

**Comment by amis92** [comment]
All good reports, except not all breachers can replace blaster with pistol - only Shas'ui can.
