### ISSUE TITLE
Adeptus Mechanicus: Points not increasing for Enginseer

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#363]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Commander levels lost their point costs. No price changes for enginseeer once I choose level 2,3 abilities

**Comment by Mad-Spy** [comment]
Seems to be working fine for me. The price increases successfully as I add higher levels.

![image](https://user-images.githubusercontent.com/29306451/61700755-f4e40680-ad34-11e9-8852-b6f95a6b8782.png)
