### ISSUE TITLE
Necrons: Missing Dynasties for Triarch Praetorian

### ISSUE THREAD

**Issue by LegateNaarifin** [BSData/wh40k-killteam#366]
**File:** Necrons.catz

**BattleScribe version:** 2.02.04.125

**Platform:** Android and PC

**Dropbox:** No

**Description:** Unable to choose a Dynasty for any Triarch Praetorians added to a roster.

**Comment by Mad-Spy** [comment]
That's correct. They can't have one, as per the rules.
