### ISSUE TITLE
Necron Dynasty doesn't show rules - can we add the text in?

### ISSUE THREAD

**Issue by shinjji** [BSData/wh40k-killteam#372]
Necron Dynasty doesn't show rules - can we add the text in? I noticed the text is in the file so I'm not sure why it's not showing up in BS. Can someone take a look?

Thanks,

**Comment by Mad-Spy** [comment]
You need to either have a valid kill team in which all models have the relevant Dynasty selected, or switch to a Command Roster and have at least one model with that dynasty selected.
