### ISSUE TITLE
Orks: Warboss options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#377]
**File:** Orks.catz

**BattleScribe version:** 2.03.00

**Platform:** Mac

**Dropbox:** Yes

**Description:** There is not an option to have a Warboss with a custom shoota/shoota and the big choppa it automatically shows a power claw and cannot be changed.

**Comment by Mad-Spy** [comment]
This is not what happens for me. The default option is Kustom Shoota and Big Choppa and this displays perfectly fine.
