### ISSUE TITLE
Adeptus Astartes: Unable to add Heavy spec to Tac Marine Gunner

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#379]
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** Tactical Marine Gunner cannot choose "Heavy" specialism, if i load old roster it is say: TMG cannot have any selection of Heavy (hiden).

**Comment by Mad-Spy** [comment]
Oops. Fixed in v22 of the Adeptus Astartes catalogue.
