### ISSUE TITLE
All: Specialists should be able to be higher than Level 1 in Open Play.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#380]
**File:** Death Guard.catz

**BattleScribe version:** 2.03.01

**Platform:** Android

**Dropbox:** No

**Description:** Commanders cannot take higher than lvl1 specialization. Same with other specialists even if you choose open play game.

**Comment by Mad-Spy** [comment]
Commanders can no longer be higher than Level 1 in Matched Play, since the
new Designer's Commentary.

However, it should work in Open Play.
