### ISSUE TITLE
Missing specialism for Broodlord Nemesis 9 Tyrantis

### ISSUE THREAD

**Issue by Floppy** [BSData/wh40k-killteam#389]
The Nemesis 9 Tyrantis set comes with a commander specialism that can only be used by that character, not by any generic broodlord. I'm not sure if N9T should be added as a separate character distinct from a Broodlord, or just to add its specialism for use by any Broodlord regardless of name. Any thoughts? Are there other factions that do this?

**Comment by Mad-Spy** [comment]
The Faction box special characters are not in any of the catalogues due to their limited availability. There are no plans to add them.

**Comment by Floppy** [comment]
OK, no problem, thanks :)

**Comment by Floppy** [comment]
Just to clarify, does "no plans to add them" mean that a PR to add it would be rejected on the basis that the data wouldn't have all of them? I'm happy to do some dev if access to time and data are the only problems.

**Comment by Mad-Spy** [comment]
Tbh, I'm not much set on implementing them at all. It's not possible to get their details outside of buying a specific limited run, and (AFAIK) most of the specific Specialisms are worse than the standard ones.

The data shouldn't be used as a rule replacement, but as a player aid. If you have bought the faction commander box, then you have the rules, and you don't need the data.

**Comment by Floppy** [comment]
Fair enough! Thanks 😃
