### ISSUE TITLE
Adeptus Astartes: Bot sniper rifle Strength needs to be increased

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#390]
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.03.03

**Platform:** Windows

**Dropbox:** No

**Description:** Stength on Bolt Snipe Rifle for the Astartes Eliminators needs updating from S$ to S5 in line with the October White Dwarf update.

**Comment by Mad-Spy** [comment]
Already fixed for next release. Giving it a couple more days to make sure there are no other issues.

**Comment by Mad-Spy** [comment]
Duplicate of #388
