### ISSUE TITLE
Astra Militarum: Characters missing Regiment selector

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#395]
**File:** Astra Militarum.catz

**BattleScribe version:** 1.04.07

**Platform:** Windows

**Dropbox:** No

**Description:** Gotfret De Montbard and Pious Vorne don't have the Millitarum Auxlia keyword like Ogryn and Ratling units do. That means they can take regimental doctrines like 'Catachan, Cadian' etc yet that option isn't available. I am not aware of any rule that forbids them from doing so.

**Comment by Maxzero100** [comment]
After reading further Gotfret De Montbard does have a specific rule preventing him from recieving regimental doctrines, Pious Vorne does not though.

**Comment by Mad-Spy** [comment]
Added for Pious, Taddeus and Espern.
