### ISSUE TITLE
Deathwatch Terminator Librarian has incorrect storm bolter cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#398]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.03.06

**Platform:** Windows

**Dropbox:** No

**Description:** Librarian in Terminator Armor when used in Deathwatch has wrong value for Storm Bolter. lists as 4 should be 8 (4 from data card, +4 for deathwatch)

**Comment by Mad-Spy** [comment]
BS app issue is now fixed as of latest BS release.
