### ISSUE TITLE
Intercessor Sergeant Weapon Selection Bugged

### ISSUE THREAD

**Issue by abust005** [BSData/wh40k-killteam#405]
Intercessor Sergeant is able to replace his bolt rifle with a power sword or chainsword, but selecting "None" for ranged weapon when choosing a power sword causes a warning requiring a selection from ranged weapons.

**Comment by Mad-Spy** [comment]
That is not correct according to the datasheet in October's White Dwarf.

![image](https://user-images.githubusercontent.com/29306451/70040798-01fee500-15b4-11ea-936f-d890ef868a7d.png)

He can replace his rifile with a chainsword or hand flamer. If he takes any other melee weapon, he must have a ranged weapon of some kind.

**Comment by RoguePlank** [comment]
Reading those 2 bullet points together makes my head hurt. That last one especially.
"If he is not equipped with a chainsword then he can be equipped with.... a chainsword."

**Comment by Mad-Spy** [comment]
Yeah, it's not the nicest way to say "he can't take 2 chainswords".
