### ISSUE TITLE
Add Kill Team Annual 2019 content

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#408]
The new 2019 Kill Team annual released with Adepta Sororitas and Ork point changes.
Thanks you all are awesome!

Extract from CODEOWNERS;
# Aeldari
- [x] Drukhari              @FarseerVeraenthis
- [x] Harlequins            @FarseerVeraenthis
- [x] Asuryani              @FarseerVeraenthis

# Chaos
- [x] Heretic Astartes    @Mad-Spy
- [x] Thousand Sons       @Mad-Spy
- [x] Death Guard         @Mad-Spy
- [x] Gellerpox Infected	 @Mad-Spy
- [x] Servants of the Abyss  @Mad-Spy

# Imperium
- [x] Adepta Sororitas @FarseerVeraenthis (written by, but not necessarily owned!)
- [x] Adeptus Astartes    @acebaur
- [x] Adeptus Mechanicus  @ohenrik
- [x] Astra Militarum     @cultiststeve
- [x] Deathwatch           @acebaur
- [x] Grey Knights        @tekton
- [x] Elucidian Starstriders	@GenWilhelm

# Other Xenos
- [x] Genestealer Cults   @GenWilhelm
- [x] Necrons              @Kohato
- [x] Orks                 @teage-like-league
- [x] T'au Empire         @amis92  
- [x] Tyranids             @GenWilhelm
- [x] Kroot @penguin20000

**Comment by FarseerVeraenthis** [comment]
Adepta Sororitas have been added just now.
The rest is WIP 😺
