### ISSUE TITLE
Adepta Sororitas wrong max value for Sister Repentia models

### ISSUE THREAD

**Issue by corias** [BSData/wh40k-killteam#413]
Battlescribe version: 2.03
Client: Windows and Android

Battlescribe shows a misleading validation error if more than 1 Sister Repentia model is added to kill team list. The actual value in the book is: no limit (ref.: Kill Team Annual 2019, pg. 107)

**Comment by Fjellvross** [comment]
They are max. 1 in the book.

**Comment by FarseerVeraenthis** [comment]
@corias please share your reference. They are Max 1 in my UK English hardcopy of the annual.

**Comment by Fjellvross** [comment]
They are max. 1 in english version, in ePub verwion, in german version...

**Comment by FarseerVeraenthis** [comment]
No reply. Closing as invalid.
