### ISSUE TITLE
Orks points update missing and missing sororitas characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#418]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Adepta sororitas:

-Not Blackstone fortress characters available (Pious Vorne, Gotfred de Montbard,etc)

Orks:

Not updated points for Nobs, Choppa, Big choppa, and Power Klaw

**Comment by FarseerVeraenthis** [comment]
I'm going to close this issue. Points from kill team annual 2019 are covered in #408 and the issue with the missing characters is covered in #417
