### ISSUE TITLE
Adepta Sororitas - Zealot issues & missing Blackstone Characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#426]
**File:** Adepta Sororitas.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** First of all thank you for you awesome work.
There're a few problems with the adepta sororitas list builder.
*Arco flagellants and their Zealot hability gets confused by the program and applies
them all the zealot speciality, being thoa tqo completely different habilities.

*No  Pious Vorne or Gottfred.  They are important for the list building,but there's
no way to put them into the list

Thats it for now, thank you!

**Comment by cmorent** [comment]
I think that the first point is fixed now, isn't it?
About Pious & Gotfred, maybe I can contribute to add both of them?

**Comment by FarseerVeraenthis** [comment]
The two characters from Blackstone Fortress are listed in the Astra Militarum cat. You can add them now by including this force in your roster. It will be valid as long as you don't add any models without the Adepta Sororitas keyword :smile:

I'll consider adding them to the Sisters cat but it is a fair bit of work to both the Sisters and Guard catalogues.

**Comment by cmorent** [comment]
Ok cool! Thanks for the answer @FarseerVeraenthis! Would be great to have them directly in the Adepta Sororitas category as for now it’s like having two rosters in one. 

Also I did notice another issue when I take a combo-something with a battle sister superior it’s shown as two weapons and not a combi weapon. Should I fill another issue for this?

Thanks for the great job anyway!
