### ISSUE TITLE
[Anon] Bug report: Chaos Daemons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#434]
**File:** Chaos Daemons.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Chaos Deamons is missing the Leardership specialism for the Bloodreaper.

**Comment by Mad-Spy** [comment]
Not if you select it as a Leader.
