### ISSUE TITLE
Orks - points cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#435]
**File:** Orks.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Ork Boy comes with slugga and choppa.  App has them costing 1 point (should be 0).  Free shoota option is correct.

**Comment by FarseerVeraenthis** [comment]
Please check Kill Team Annual 2019. A Choppa now costs 1 point for everyone except Big Mek and Nob models.
