### ISSUE TITLE
Warhammer 40,000 Kill Team: Commanders count as Specialists?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#439]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Thé actual version count the Commander specialism in the max of allowed specialists, but it shouldn't. See commander rulebook p14 : " Commander must have a specialism – this does
not count towards the maximum number of specialists
you can include in a kill team. [...] A kill team can still
only include one of each kind of specialist. "

**Comment by Mad-Spy** [comment]
I'm not able to replicate this. Are you having the problem with a particular catalogue? 
Neither Leaders nor Commanders count towards the maximum number of Specialists in any of the catalogues I've tried.

**Comment by Mad-Spy** [comment]
Closing as this is not reproducible and OP has not replied.
