### ISSUE TITLE
Incorrect point cost for Grey Knights Pair of Nemesis Falchions

### ISSUE THREAD

**Issue by jimokeane** [BSData/wh40k-killteam#440]
As per official errata, you can only ever buy a pair of falchions, and the pair costs 1 point. 
https://www.warhammer-community.com/wp-content/uploads/2019/08/kill_team_errata_en.pdf

So the point cost should be changed from 2.0 to 1.0.

**Comment by Mad-Spy** [comment]
This errata was released before the Annual, and is therefore superseded by it.
The cost in the Annual is 1pt for a "Nemesis Falchion", not a pair.
Therefore the cost in the app is correct until GW release another errata changing it.

**Comment by jimokeane** [comment]
That is not correct. Why would they correct it in the errata, and then
change it back. Everyone agrees this is a copy/paste error in the annual.
