### ISSUE TITLE
Adeptus Astartes: Suppressors should be able to pick Stealth

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#454]
**File:** Adeptus Astartes.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** The option for Surpressors and Surpressors Seargent to pick the Stealth Speciality is missing.

**Comment by Mad-Spy** [comment]
This option was removed from Suppressors in the Elites August 2019 update.
