### ISSUE TITLE
Deathwatch -Terminator point values

### ISSUE THREAD

**Issue by laichimirum** [BSData/wh40k-killteam#456]
In the current data version for terminators an additional 4 point is added for the powerfist, however according to the book, the addition weapon costs only added for ranged weapons in case terminators are included in a deathwatch kill team.

**Comment by Mad-Spy** [comment]
Marine power fists cost 4pts for all models that take them (except Captains), as per the Annual. Default wargear costs are not included for the majority of models in Kill Team.
