### ISSUE TITLE
Space Wolves Grav weapons

### ISSUE THREAD

**Issue by RoguePlank** [BSData/wh40k-killteam#469]
Astartes with the Space Wolves chapter should not be able to equip the Combi-Grav or Grav pistol on any of their units, but Grav-gun is still allowed. According to page 42 in Elites.

Currently, equipping a combi-grav or grav pistol doesn't cause any errors.

**Comment by Mad-Spy** [comment]
Only the models in the Elites book are affected by the rules in the Elites book. As such, the only models affected by this rule are those on the Veteran datasheet and these correctly hide the grav options when they are made Space Wolves.

**Comment by RoguePlank** [comment]
If you select the weapons before selecting the chapter, they don't disappear or raise error flags.
