### ISSUE TITLE
Kill Team Astartes Roster 

### ISSUE THREAD

**Issue by hardworlder** [BSData/wh40k-killteam#495]
Relic blades are missing from the Vanguard Veteran selection, and Deathwatch cannot take Vanguard Sergeants.

**Comment by Mad-Spy** [comment]
1. Vanguard Veterans cannot take Relic Blades, only Vanguard Sergeants.
2. You are correct, Deathwatch cannot take Vanguard Sergeants, as per the August 2019 Elites update.
