### ISSUE TITLE
Reference: Catalogue Maintainers

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-killteam#5]
Below is a list of all factions according to who has volunteered to maintain them.

### Up for grabs
*None*

---

### Currently Allocated
*(?) denotes unconfirmed*

@acebaur
Adeptus Astartes
Deathwatch (?)

@GenWilhelm
Genestealer Cults
Tyranids

@Mad-Spy
Death Guard
Thousand Sons
Heretic Astartes

@FarseerVeraenthis
Asuryani
Drukhari
Harlequins

@amis92
T'au Empire ~~(?)~~ *confirmed*

@tekton
Grey Knights

@Kohato
Necrons

@Cultiststeve
Astra Militarum

@ohenrik
Adeptus Mechanicus

@teage-like-league
Orks

**Comment by ohenrik** [comment]
I can sign up for maintaining Adeptus Mechanicus

**Comment by GenWilhelm** [comment]
@teage-like-league, shall I put you down as the maintainer for Orks?

**Comment by teage-like-league** [comment]
Sure thing, I can take of them. I am a bit new at this, so I may have some questions though

**Comment by Mad-Spy** [comment]
Converted above data into a CODEOWNERS file, as the maintainers seem to be pretty set now.
