### ISSUE TITLE
Eisenhorn points value

### ISSUE THREAD

**Issue by RoguePlank** [BSData/wh40k-killteam#504]
Inquisitor Eisenhorn is showing as 80pts for Admech, 70pts for other teams. Pretty sure he's 70pts at level 1 across the board.

**Comment by RoguePlank** [comment]
[EISENHORN.pdf](https://github.com/BSData/wh40k-killteam/files/4902172/EISENHORN.pdf)

**Comment by RoguePlank** [comment]
![Screenshot_20200710-102222.jpg](https://user-images.githubusercontent.com/6419422/87139079-516a6980-c297-11ea-8067-03965abe3fd7.jpg)

Doesn't seem to happen all the time, can't figure out what's causing it.

**Comment by RoguePlank** [comment]
Here's a link to a roster that shows him as 80pts

[https://www.dropbox.com/s/qztzdio1uw5zdkx/AC30%20-%20Priests%20of%20the%20Omnissiah%2011.rosz?dl=0](url)

**Comment by Mad-Spy** [comment]
That's what happens when some idiot doesn't check his conditions are set to the correct scope.

He was picking up level selections from other Commanders.
