### ISSUE TITLE
[Anon] Bug report: Sisters of Silence.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#506]
**File:** Sisters of Silence.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Battlescribe version v2.03.21.166

Sisters of Silence either 100pt or unlimited point roster always shows Roster Validation Error "Must have 3 more selections from Model (minumum 3)" Roster created with 1 leader 3 specialists and then 3 non-specialist. This error also appears when points set to unlimited.

**Comment by c00ky1970** [comment]
[Sister of Silence-D.zip](https://github.com/BSData/wh40k-killteam/files/4907158/Sister.of.Silence-D.zip)

Example roster that generates the error message

**Comment by Mad-Spy** [comment]
/release
The Sisters start modelling
