### ISSUE TITLE
Company veterans weapons and spacewolves

### ISSUE THREAD

**Issue by RoguePlank** [BSData/wh40k-killteam#507]
Sorry to pull you back to page 40 of Elites again, it's a wording nightmare.

Company vet is armed with bolt pistol and chainsword.

Book says they can:
- swap bolt pistol for another pistol or melee weapon.
- swap chainsword for a boltgun **or** 1 combi/special/pistol/melee weapon

Company Veterans are currently able to select a boltgun **and** any combi/special weapon, so they have 2 full guns.

I believe the option to select a boltgun should be hidden if the user selects any gun from combi or special list, or cause the same "max 0" error that the vet sergeant triggers if he tries to pick a combi and a bolter.

I found it odd that my wolves company vet was able to take a bolter and a storm bolter, making him a ranged power house, so decided to double-check the book again.

Separate issue: error flag still appears for more than 4 company veterans when spacewolves chapter is selected. Spacewolves get unlimited company vets, again on page 40. So can disable that error if all the company vets have chapter = spacewolves.

**Comment by Mad-Spy** [comment]
I've fixed the weapon rules, but it's impossible to successfully validate the Veteran exception for Wolves without duplicating Vets like I did for the Terminators. It's not possible to check whether all Veterans are Space Wolves.

**Comment by RoguePlank** [comment]
That's ok, the weapon fix was the main issue. Got excited thinking I could arm a company vet with 2 guns, get like 6 bolter shots out of him for just 2 points on the storm bolter as the bolter was free. But alas, 'twas not to be.

**Comment by Mad-Spy** [comment]
BTW, I joined the Glass Half Dead Discord, so you can ping me on there, or on the BSData Devs one if you have any questions.

**Comment by RoguePlank** [comment]
That's fine, I'm on both. Would you prefer I ping you on there instead of raising an issue here? I don't raise an issue unless I find a genuine problem.

**Comment by Mad-Spy** [comment]
Raising an issue for actual problems is best, but just general "why is it like this?" type stuff you can ping me.
