### ISSUE TITLE
Kroot: Incorrect specialisations for Krootox Rider

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#509]
**File:** Kroot.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Krootox rider should have the option to be a Veteran Specialist and Combat specialist, the Heavy specialist needs to be replaced with Veteran specialist.
Thank you in advance

**Comment by Mad-Spy** [comment]
Looks like this got changed between the WD issue and the Annual, and the update got missed.
