### ISSUE TITLE
bug report - you can add more than 1 sniper specialist to your killlteam in battlescribe

### ISSUE THREAD

**Issue by xamo1337** [BSData/wh40k-killteam#522]
As stated above, you are currently able to add more than 1 sniper specialist to your killlteam which is against the rules (p.66 killteam core rulebook: "Each model's specialism must be unique - you cannot have two models with the same specialism in your killteam".). It appears as it just works with certain factions in battlescribe right now, e.g. necrons, drukhari and asuryani. 

Thanks for fixing :)
![necronss](https://user-images.githubusercontent.com/46102376/97482700-c650d480-1956-11eb-81c5-6ded3f42e124.PNG)

**Comment by Mad-Spy** [comment]
Turns out this was majorly broken across almost every catalogue. Thanks for picking this one up!
