### ISSUE TITLE
Death Guard: Poxwalkers can't be Non-Specialists

### ISSUE THREAD

**Issue by MaxPowers1337** [BSData/wh40k-killteam#527]
File: Death Guard.cat

BattleScribe version: v2.03.21.166

Platform: Windows/PC

Dropbox: Yes

Description: Poxwalker are only choosable as Specialists. Not as Non-Specialists. On mobile/android using the same data file/release everything works.

![image](https://user-images.githubusercontent.com/74922602/99987296-94455d80-2db0-11eb-9a5a-a9f755e65e34.png)

**Comment by MaxPowers1337** [comment]
Same goes for the Plague Marine Gunner for example. When editing the Roster on mobile everything works. Loading the same roster file via dropbox on windows works, too. Battlescribe also not shows errors on this items.

**Comment by Mad-Spy** [comment]
Try maximising your window...

![image](https://user-images.githubusercontent.com/29306451/99988064-17fb4c00-2da9-11eb-91a4-ff87e676e791.png)
