### ISSUE TITLE
UX Suggestion: Adeptus Astartes.cat - Scout Multiple Weapons

### ISSUE THREAD

**Issue by greenmtvince** [BSData/wh40k-killteam#547]
Probably more of UX suggestion than a bug:
Scouts can take multiples of combat knife and boltgun.  This does trigger the appropriate roster Error: 'Scout has X too many selections from Weapon Options'  Perhaps a checkbox instead of increment would be a more logical UI element here.

**Comment by Mad-Spy** [comment]
Fixed in next release.
