### ISSUE TITLE
Deathwatch Black Shield Weapon Exchange

### ISSUE THREAD

**Issue by dairelavelle1** [BSData/wh40k-killteam#555]
BattleScribe v2.03

Kill Team v2.0.1

Android

If a black shield exchanges its boltgun for wargear from the "melee weapons" list, and any wargear is selected under exchange power sword, The error is "Black Shield has 1 too many selections from Exchange power sword (maximum 1)" 

If a black shield exchanges its power sword for wargear from the "melee weapons" or "pistols" lists, and any wargear is selected under exchange boltgun, the  error is "Black Shield has 1 too many selections from Exchange boltgun (maximum 1)"

Special weapons and combi-weapons work with storm shields but melee weapons and pistols don't

**Comment by Mad-Spy** [comment]
Already fixed for next release
