### ISSUE TITLE
Deathwatch Veteran's Exchange Boltgun options counting as Exchange Power Sword

### ISSUE THREAD

**Issue by Kongield** [BSData/wh40k-killteam#556]
When choosing wargear for either Deathwatch Veteran, Deathwatch Veteran Gunner, Watch Sergeant or Black Shield, if you choose to exchange your Boltgun for a Storm Shield, any melee weapon or any pistol, it counts as both Boltgun and Power Sword replacement and displays an error

**Comment by Mad-Spy** [comment]
Fixed in next release.
