### ISSUE TITLE
Adeptus Astartes v36 Eliminator and Eliminator Seargent has wrong "BS" stats

### ISSUE THREAD

**Issue by xamo1337** [BSData/wh40k-killteam#569]
Just noticed that the Eliminator and Eliminator Seargent has a "BS" stat of 2+ with the new Pariah Nexus update instead of 3+ (it is in the official pariah nexus book on page 83) In BattleScribe with the latest update it still has a BS of 3+.

Thanks for fixing :)

**Comment by Mad-Spy** [comment]
Fixed in current release, v2.0.4. Update your data.

**Comment by Mad-Spy** [comment]
Actually, looks like that release still hasn't made it to Appspot. It'll turn up eventually.
