### ISSUE TITLE
X-101 and UR-025 cannot select a Forge World

### ISSUE THREAD

**Issue by ParoniE** [BSData/wh40k-killteam#570]
RAW they should benefit from Forge World bonuses.

Also Battlescribe2TTS can't handle X-101 for some reason.

**Comment by Mad-Spy** [comment]
Battlescribe2TTS is not affiliated with any of the data authors or Battlescribe itself. You'll need to take it up with the developers of that tool.

**Comment by ParoniE** [comment]
> 
> 
> Battlescribe2TTS is not affiliated with any of the data authors or Battlescribe itself. You'll need to take it up with the developers of that tool.

Reported that there. The part about X-101 and UR-025 not being able to have a Forge World selected is still valid.

**Comment by Mad-Spy** [comment]
Turns out the X-101 thing actually was on this end. He wasn't properly marked as a Model. Now fixed.
