### ISSUE TITLE
Necrons - "No options to add ... anything to the list"

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#58]
**File:** Necrons.catz

**BattleScribe version:** 1.45.32

**Platform:** Android

**Dropbox:** No

**Description:** The information for Necrons do not display properly. There are no options to add any Specialists, models, anything to the list. I have tried updating the file,  but that does not seem to work. Several of my friends report the same thing happening to them.

**Comment by FarseerVeraenthis** [comment]
Is your Battlescribe version correct??
If so, I don't think these CAT files will work on version 1, you need to upgrade to version 2!!
