### ISSUE TITLE
Wrong specialisms on admech sicarians

### ISSUE THREAD

**Issue by Afinostux** [BSData/wh40k-killteam#581]
The sicarian infiltrators and ruststalkers incorrectly show Sniper instead of Veteran as a specialism option.

**Comment by Mad-Spy** [comment]
Fixed at least a couple of releases ago. Update your data.

**Comment by Afinostux** [comment]
Explain this then. Deleted and redownloaded before testing.

-Austin

**Comment by Mad-Spy** [comment]
Your attachment didn't come through, however I now see the problem. It's not the standard models (which I did fix), it's just the Princeps which I forgot.
