### ISSUE TITLE
Tau DS8 Support Turrets

### ISSUE THREAD

**Issue by SirHazzington** [BSData/wh40k-killteam#583]
The Tau Kill Team can take one DS8 Support turret for Breachers and Fire Warriors, The limit of 1 applies to each unit, not shared between them. 
You should be able to take 1 for Fire Warriors and 1 for Breachers.
Thanks!

**Comment by Mad-Spy** [comment]
I'm afraid you're incorrect. This was explicitly addressed in the Designer's Commentary and it was stated that you can only have 1 in the entire kill team. See p6 of the linked doc.

https://www.warhammer-community.com/wp-content/uploads/2019/08/kill_team_designers_commentary_en.pdf
