### ISSUE TITLE
Warhammer 40,000 Kill Team: Named Commanders should have access to Commander Traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#586]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** All Commanders should be able to choose up to three Commander Traits from those listed on page 53 of Pariah Nexus when they are added to your roster. 

In addition Elucia Vhane (Elucidian Starstriders) and Vulgar Thrice-Cursed (Gellarpox Infected) each have two of their own unique additional Commander Traits to choose from in Rogue Trader.

**Comment by Mad-Spy** [comment]
Fixed for named commanders

Elucia and Vulgar already had access to their additional traits.
