### ISSUE TITLE
[data issue] Deathwatch Veteran Storm bolter Cost

### ISSUE THREAD

**Issue by straef** [BSData/wh40k-killteam#587]
when replacing the boltgun on the deathwatch veteran with the storm bolter, the cost is listed as 2pts. according to my reading of the datasheets indicates that the storm bolter should be 6pts for this replacement. am i missing something or is the points incorrect?

the cost for storm bolter on the company veteran is 6pts, which agrees with my reading of the datasheets. as i read it all non-commanders that can get storm bolters do so at a cost of 6pts, and commanders get the storm bolter at either 4pts (captain & chaplain terminators) or 8pts (librarian terminator).

deathwatch veteran is the only model i see with this issue.

**Comment by Mad-Spy** [comment]
Only models that began as ADEPTUS ASTARTES have to pay for SIA, as per the rules.

**Comment by straef** [comment]
Aquila Kill Team
When you add an ADEPTUS ASTARTES model (excluding a Scout, Sternguard Veteran or Tactical Marine) to your command roster (and create its datacard) you can choose for it to have the DEATHWATCH Faction keyword instead of the ADEPTUS ASTARTES Faction keyword. If you do so, it gains the Special Issue Ammunition ability **but you must use the Deathwatch points values for its ranged weapons**.

Bolt pistol | **2pts** | 12" | Pistol 1 | 4 | 0 | 1 | -


is the above (source: http://wahapedia.ru/kill-team/factions/deathwatch/) incorrect?

**Comment by Mad-Spy** [comment]
No, that is not incorrect.

Deathwatch Veterans do not start with the ADEPTUS ASTARTES Faction keyword, so you can't replace it with DEATHWATCH. As per that rule, the additional point cost only applies if you change the keyword.

**Comment by straef** [comment]
thank you. good to know. wahapedia is my only source of rules at the moment, so it was all i had to go on.
