### ISSUE TITLE
Deathwatch Primaris Lieutenant should not have Space Wolves or Dark Angels Lieutenant wargear options

### ISSUE THREAD

**Issue by balderis47** [BSData/wh40k-killteam#589]
Deathwatch Primaris Lieutenant can not be equipped with special issue bolt carbine and power axe or with plasma pistol because Space Wolves or Dark Angels Lieutenant can not have Deathwatch keyword (p. 61 Pariah Nexus)

**Comment by Mad-Spy** [comment]
Correct, and if you attempt to do so, your Roster will have an error.

**Comment by balderis47** [comment]
> Correct, and if you attempt to do so, your Roster will have an error.

ОК!
