### ISSUE TITLE
Tyranids - "Too many flesh hooks" when taking multiple Lictors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#59]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** When making a tyrranid kill team list with multiple Lictors, you get an error for having too many flesh hooks.

**Comment by stayduned** [comment]
Jepp you're right, also with tyranid warriors
