### ISSUE TITLE
Space Marine Librarian Force Weapons don't have new Pariah Nexus boosts

### ISSUE THREAD

**Issue by academicchris** [BSData/wh40k-killteam#592]
E. G. the Force Sword should be a +1S weapon, etc.

**Comment by Mad-Spy** [comment]
The stats were changed when PN was released and have been in every release since then.

Can you upload a screenshot showing the problem?

**Comment by academicchris** [comment]
Oh weird, it only appears on the Primaris Librarian now that I'm checking: 

![Primaris Typo](https://user-images.githubusercontent.com/68138973/115231344-0fe6d480-a0db-11eb-9c26-63ea59d4ceb1.png)
