### ISSUE TITLE
No Ammo runts in Kill Team Campaign Configurations

### ISSUE THREAD

**Issue by Boozebeard** [BSData/wh40k-killteam#597]
As in title; there is no option to add ammo runts to a campaign kill team roster or kill team list.

**Comment by Mad-Spy** [comment]
Ammo Runts can never be Specialists (as per their rules) so they only appear in Nob Fire Teams.

**Comment by Boozebeard** [comment]
OH, sorry I did not realised the Ammo Runts were part of the Nob data sheet. My bad.
