### ISSUE TITLE
Sterngurd Sergeant weapons

### ISSUE THREAD

**Issue by F1renDev** [BSData/wh40k-killteam#600]
BattleScribe version: 2.03.25
Adeptus Astartes Sternguard Sergeant can no longer (as of pariah nexus) exchange boltgun for any special weapon.
![Screenshot_1](https://user-images.githubusercontent.com/47530368/120108744-39c9f700-c16f-11eb-87f9-0ffefe9ff66d.png)

**Comment by Mad-Spy** [comment]
Not sure what you mean. The Sternguard never had a "boltgun". They have always had a "special issue boltgun". The erratum fixed the fact that the datasheet referenced a "boltgun", meaning that technically Sternguard were unable to swap their weapon at all.
