### ISSUE TITLE
KT2021 Progress

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-killteam#606]
- [x] Brood Coven
- [x] Cadre Mercenary
- [x] Chaos Daemons
- [x] Commorrite
- [x] Craftworld
- [x] Death Guard
- [x] Ecclesiarchy
- [x] Forge World
- [x] Greenskin
- [x] Grey Knights
- [x] Hive Fleets
- [x] Hunter Cadre
- [x] Imperial Guard
- [x] Kommando
- [x] Space Marine
- [x] Talons of the Emperor
- [x] Thousand Sons
- [x] Tomb World
- [x] Traitor Space Marines
- [x] Troupe
- [x] Veteran Guardsmen

**Comment by PhilKaBoom** [comment]
Hi @Mad-Spy, maybe I can assist u from wednessday on ... Pleased answer If u wish
