### ISSUE TITLE
Range icons for KT2021 not showing on MacOS

### ISSUE THREAD

**Issue by eddbc** [BSData/wh40k-killteam#607]
Not sure if this is something that can be fixed in the data catalogue or if it's something for Battlescribe in general, but some of the range icons being used do not show when using the Battlescribe MacOS client.

![image](https://user-images.githubusercontent.com/5603957/130045723-548b0630-4a53-4e3a-af83-b7f0b5ec116d.png)
Operative has a Movement of 3 Circle, and the pistol has a range of Pentagon.

Same icons display fine on other platforms.

**Comment by Mad-Spy** [comment]
Probably not a whole lot that can be done in the data, unfortunately without taking out the symbols entirely. Is it just the circle that's not rendering?

**Comment by eddbc** [comment]
Circle and the Pentagon it seems to be. Triangle works fine

**Comment by Floppy** [comment]
I'm on MacOS, so I'll try a couple of things, see if I can fix it in the data, but I suspect that the issue will be with Battlescribe. I'll report back later!

**Comment by Floppy** [comment]
OK, did some tests.

|Symbol|Unicode|works on MacOS|
|-|-|-|
|▲|U+25B2|yes|
|-|-|-|
|⬟|U+2B1F|no|
|⭓|U+2B53|no|
|⬠|U+2B20|yes|
|-|-|-|
|⬤|U+2B24|no|
|●|U+25CF|yes|
|-|-|-|
|⬛|U+2B1B|yes|
|■|U+25A0|yes|
|-|-|-|
|💀|U+1F480|no|

I can't see a pattern as to why some of the distance symbols don't work, it must be a Battlescribe unicode/font thing, I think. None of the emoji range seem to work.

I suggest we report this up to Battlescribe, but in the meantime if we want to fix for macOS users, change to using  ▲ ⬠ ● and ■. It's not a consistent set, and they render a bit inconsistently size-wise in Battlescribe itself, but they do work.

**Comment by Floppy** [comment]
I've reported it upstream ☝🏻

**Comment by Floppy** [comment]
Incidentally, it's not a problem on the iOS app, though I guess that's a completely different Battlescribe codebase.
