### ISSUE TITLE
Veteran guardsmen needing a veteran trooper check

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k-killteam#608]
Veteran guardsmen killteam consists of 10 guys and an ancillary support. That support consists of 4 normal troopers (cannot change them for anything else) plus 2 fire supports you can choose at the start of the game. Therefore this killteam should make sure you select both the ancillary support and 4 trooper veterans.

Likewise, it doesn't check that I have a leader, which is also compulsory

As a suggestion, this killteam used to have a reference sheet with the orders and fire support options and they were removed in a patch. I suggest returning them, since they're pretty useful

**Comment by Mad-Spy** [comment]
1. Fixed. It'll now force you to take 4 Troopers.
2. None of the Fire/Kill Team ForceEntries make you do this. I'm trusting to people's common sense.
3. Not removed, never added to the Kill Team ForceEntry. Now fixed.

**Comment by GuillermoDiazGarcia** [comment]
Disregard the first point. Apparently I read it wrong.

You take EITHER 4 troopers OR 2 fire support elements. The text is slightly ambiguous and I thought it was both, but I was wrong I think
![image](https://user-images.githubusercontent.com/55704459/130104540-ca3b3548-4aa1-4783-8730-5dce94f439e9.png)

**Comment by Mad-Spy** [comment]
I mean it'll force you to take the troopers if you select the support option.
