### ISSUE TITLE
T'au Empire: Can take too many DS8 turrets

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#61]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
- ~~XV25 Stealth Battlesuit should not have the Medic specialist option~~
- ~~Fire Warrior Breacher should have the Medic specialist option~~
- ~~Fire Warrior should have the Medic specialist option~~
- ~~Pathfinder should have the Medic specialist option~~
- ~~MV1 Gun Drone gives an error saying "MV1 Gun Drone has 1 too many selections of Pulse carbine (maximum 1)" and this should not be an error that shows up since the Gun Drone has 2 normally~~
- Currently on Battlescribe, you are able to have multiple DS8 Tactical Support Turrets if you have multiple Fire Warrior Shas'la on your list but the rulebook states a maximum of one per killteam.

**Comment by Mad-Spy** [comment]
Issues struck through have already been fixed.
