### ISSUE TITLE
2021 - Space Marine: Krak grenades missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#625]
**File:** 2021 - Space Marine.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Intercessors can't equip Krak Grenades.

Intercessors should be able to equip Krak Grenades.

**Comment by GuillermoDiazGarcia** [comment]
Not just intercessors, all space marines are missing their krak grenades
