### ISSUE TITLE
 Hunter Cadre: Shas'ui pulse blaster BS

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#637]
**File:** 2021 - Hunter Cadre.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The weapon skill for the fire warrior shas`ui using the pulse blaster,  pulse rifle and pulse carbine should be 3+.  It's currently 4+

**Comment by fivaldrood** [comment]
https://github.com/BSData/wh40k-killteam/pull/638#issue-722042907
