### ISSUE TITLE
Ecclesiarchy: Plasma pistol profile error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#640]
**File:** Sisters of Silence.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** 

Battle Sister Superior Plasma Pistol - Standard should not have Limited
Battle Sister Superior Plasma Pistol - Standard, and Supercharge should have a WS/BS of 2+.

**Comment by Mad-Spy** [comment]
Fixed
