### ISSUE TITLE
Talons of the Emperor: Plasma pistol profile incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#641]
**File:** Sisters of Silence.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Battle Sister Superior Plasma Pistol - Standard, and Supercharge has a WS/BS of 3+.
Battle Sister Superior Plasma Pistol - Standard, and Supercharge should have a WS/BS of 2+.

**Comment by Mad-Spy** [comment]
Added to #640
