### ISSUE TITLE
Hunter Cadre: DS8 Tactical Support Turret

### ISSUE THREAD

**Issue by az-chris** [BSData/wh40k-killteam#646]
When selecting a DS8 Tactical support turret you are presented with choices for None, Missile Pod, or Smart missile system. The turret currently recieves both smart missiles and the missile pod and does not need to decide between them

**Expected behavior**
Adding a support turret should be added with both missile weapons with no choice between them

**Screenshots**
![image](https://user-images.githubusercontent.com/12321884/131433250-82e21c7a-820a-4d57-9a0f-72394baabf87.png)

**Device and data (please complete the following information):**
 - OS: Windows 10 Pro Build: 19042.1165
 - BattleScribe version  2.03.21.166
 - Release version v3.0.0

**Additional context**
Drones as described on page 137 do not present a wargear choice for missile turrets

**Comment by Mad-Spy** [comment]
No. Just, no.
