### ISSUE TITLE
[Anon] Bug report: 2021 - Greenskin.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#656]
**File:** 2021 - Greenskin.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Boy fire team is allowed to select up to 10x Gretchin; but the max should be 2x. 

For ref, the rule is "Instead of selecting one BOY FIGHTER operative in each BOY fire team, you can select two BOY GRETCHIN operatives."

**Comment by Mad-Spy** [comment]
That does not limit you to two Gretchin. You can take 2 for each Boy you do not take.
