### ISSUE TITLE
Lictor flesh-hooks should not count towards maximum flesh-hooks on Genestealer units

### ISSUE THREAD

**Issue by banoffeepy** [BSData/wh40k-killteam#66]
When adding Genestealer to a list and selecting flesh hooks as an option. the "too many selections of flesh hooks" error is displayed when a lictor is also in the list (as they come with flesh hooks as standard)

Android mobile
file version: Killteam (2018) 1.2.0

**Comment by FarseerVeraenthis** [comment]
This is a duplicate of #59 and will be fixed in the next release :smile:

**Comment by banoffeepy** [comment]
My bad - thanks for the work
