### ISSUE TITLE
[Anon] Bug report: 2021 - Commorrite.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#660]
**File:** 2021 - Commorrite.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Wych teams can only select one of each drug, but can put multiples of the same drug on one operative.

**Comment by Mad-Spy** [comment]
Unable to reproduce in current release. Please update your data.
