### ISSUE TITLE
[Anon] Bug report: 2021 - Troupe.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#666]
**File:** 2021 - Troupe.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Player (Leader) is unable to equip a power weapon, despite the option being available in the Kill Team Compendium.

**Comment by Mad-Spy** [comment]
Fixed in current release. Update your data.
