### ISSUE TITLE
Duplicate Specialism Validation

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-killteam#67]
Affected Catalogues:

- [x] Necrons
- [x] Thousand Sons
- [ ] T'au Empire

There's currently a bug in BattleScribe that causes constraints to not be validated on selections with a conditional modifier that sets hidden using the `Not Instance Of` condition type.

The above catalogues use this type of condition, meaning that some of their specialisms are not validating their `Max 1 in Force` constraint that is active in a Battle-forged Kill Team configuration.

**Comment by Jonskichov** [comment]
@GenWilhelm @DrTobogganMD 

Can you confirm if this is still an issue, and if so provide steps to reproduce? I'm having no luck. Take a look at my comment here: https://github.com/BattleScribe/Release/issues/24#issuecomment-464359208

**Comment by GenWilhelm** [comment]
Using data from before this issue (such as v1.0.2, as you mentioned):

1. Add 2 Deathmarks as specialists.
2. Select Sniper specialism for both Deathmarks.

A warning should appear, as Sniper has a `max 1 in Force` constraint set when you are making a "Battle-forged" Kill Team (such as `Matched Play: Kill Team`).

![not_instance_of](https://user-images.githubusercontent.com/22036809/52902982-4b8e6700-3210-11e9-8b15-231c8e439e09.png)
