### ISSUE TITLE
Asuryani: Ranger counts as 2 models in roster

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-killteam#68]
Ranger is counting as two models in a roster for some reason.

If I add 11 rangers, I am told that I have "2 too many selections from Model (max 20)".

**Comment by FarseerVeraenthis** [comment]
That doesn't make sense...! But I'll look into it :smile:

**Comment by amis92** [comment]
Something somewhere has "Model" category checked when it shouldn't :)

**Comment by FarseerVeraenthis** [comment]
it was the rifle. I had to delete it and enter it again...!
