### ISSUE TITLE
Hunter cadre Pathfinder leader Shas'ui BS to be corrected

### ISSUE THREAD

**Issue by XC18** [BSData/wh40k-killteam#682]
**Describe the bug**
The BS balistic skill  of the Tau Pathfinder leader is normally 3+ to hit with a Pulse carbine (see in the Compendium).
Battlescribe still shows 4+ like the standard troop.

**To Reproduce**
1. setup a tau "Hunter cadre' Fire team
2. add a leader Shas'ui  & check his stats.

**Comment by Mad-Spy** [comment]
Working correctly in current release.
