### ISSUE TITLE
Traitor Space Marines - Aspiring Champion - 'Upgrade' instead of 'Model'

### ISSUE THREAD

**Issue by g3rg** [BSData/wh40k-killteam#687]
Aspiring Champion in "2021 - Traitor Space Marine.cat"  selectionEntry is set as type "upgrade", instead of "model":

    <selectionEntry id="b532-b9b4-af08-5935" name="Aspiring Champion" hidden="false" collective="false" import="true" type="upgrade">

Am contributing to https://github.com/Floppy/dataslate and it fails to load due to the incorrectly typed operative.

I've forked the repository and can create a pull request for this, but wasn't 100% sure of how this repository is maintained.

Thanks.

**Comment by Floppy** [comment]
Oops, thought I'd got all these, I must have missed one!
