### ISSUE TITLE
Release 3.0.7 extracted sha256 do not match for some files

### ISSUE THREAD

**Issue by andychin7777** [BSData/wh40k-killteam#693]
**Description**

SHA256 hash does not match for 
release 3.0.7
2021 - Thousand Sons.cat
master branch SHA256: AD1CB67CCA671FD994D274AC3E51D803947C104091AB512E9DADF0C1F298EF21
release extract SHA256: EF8745FDD7E687F51157BBDE36B6D9895DA1D96295E3C447D7C2D8B76AAF58B3

2021 - Hunter Clade.cat
master branch SHA256: 886E581877D1234DEA7B19FE2BA4CED2CE248E0B7C086D3A8C793EA0F3723FEF
release extract SHA256: 9C6AF386A37DA74DC5D0186B16ECB61AB89C3F96C6E274A962965F9D1C3DC025

**To Reproduce**
download the release version 3.0.7 (latest at time of bug writing) extract the 
2021 - Thousand Sons.cat
2021 - Hunter Clade.cat
files,
generate sha256 from the extracted files, as they will be as stated in description above.

**Expected behavior**
SHA256 should match for these files or be the same as the SHA256 in https://github.com/BSData/wh40k-killteam/releases/download/v3.0.7/wh40k-killteam.catpkg.json

**Comment by FarseerVeraenthis** [comment]
The data has been updated since release: [https://github.com/BSData/wh40k-killteam/releases/tag/v3.0.7](https://github.com/BSData/wh40k-killteam/releases/tag/v3.0.7)

**Comment by Mad-Spy** [comment]
You realise that the json file has the hashes of the zipped versions of the files, not the unzipped ones, right?
