### ISSUE TITLE
Adeptus Mechanicus: Data-tethers and Omnispex Availability

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k-killteam#71]
Alphas and Gunners should not be able to take an Enhanced Data-tether or an Omnispex.

**Comment by GenWilhelm** [comment]
"Skitarii Ranger" refers to the specific model type - ie. not a Ranger Gunner, or Ranger Alpha.
Options that are available to anyone on the datasheet use the wording "This model" (eg. on the Sicarian Infiltrator datasheet).

**Comment by ohenrik** [comment]
Ah, i see :) Ill fix it.

**Comment by ohenrik** [comment]
I created a pull request, but should i in the future just merge these small fixes at once? or is it better to continue with pull requests so that some one can review the changes?

**Comment by GenWilhelm** [comment]
You're the maintainer, so it's your call how you want to handle it.

As a Collaborator, I'm not sure if you have permission to merge into master (as it's protected). If you don't, one of the admins will merge it when they see it (or come and shout at one of us on gitter 😅 ).
