### ISSUE TITLE
Kill Team v3.0.9 Missing Weapon Option

### ISSUE THREAD

**Issue by dunedon** [BSData/wh40k-killteam#720]
**Describe the bug**
Talons of the Emperor - Sister of Silence Superior is missing the Gun Butt that goes with Boltgun and Flamer.

**To Reproduce**
1) Add Silence Superior to Talons of the Emperor Fire Team.
2) Select Boltgun (or Flamer)

**Expected behavior**
Expect to see both the selected ranged weapon, and the gun butt listed (as it is for Prosecutors)

**Screenshots**
![image](https://user-images.githubusercontent.com/513246/147988621-5a5f37e5-062e-4052-945f-9e0311e95a7b.png)

**Device and data (please complete the following information):**
 - OS: Desktop
 - BattleScribe v2.03.21.166
 - Release version 3.0.9

Edit: It does apparently show on the highlight text, and in the export, just not on the screenshot (as shown above).

**Comment by dunedon** [comment]
so I see it now, for some reason it's another level deeper, closing this now.

**Comment by Mad-Spy** [comment]
The Superior _always_ has a choice of melee weapons; she is not forced to take the gun butt with her rifles, unlike other models.
