### ISSUE TITLE
Harlequins not displaying equipment

### ISSUE THREAD

**Issue by Alarrick** [BSData/wh40k-killteam#725]
Hey all, Harlequin Troupe Kill Teams don't appear to be displaying Equipment as available options

**Comment by Mad-Spy** [comment]
It's definitely there. Make sure you've selected to build a Kill Team, not a Roster.

![image](https://user-images.githubusercontent.com/29306451/151142704-945e25aa-4780-4777-ac93-402a44b13d2b.png)
