### ISSUE TITLE
Death Korps of Krieg Missing

### ISSUE THREAD

**Issue by Loweville** [BSData/wh40k-killteam#730]
Hello,

Just been looking for Death Korps of Krieg in the Astra Militarum force and there is no entries at all, is there any chance for it to be looked at in the future?

Thanks in advance

**Comment by Mad-Spy** [comment]
There is no "Death Korps of Krieg" Kill Team. I suspect you're referring to the "Veteran Guardsman" team, which has never been part of the Compendium "Astra Militarum" faction.
