### ISSUE TITLE
Wyrmblade list - missing equipment options

### ISSUE THREAD

**Issue by CaiusCai** [BSData/wh40k-killteam#733]
It is not currently possible to assign assign any equipment  to any operatives in the Genestealer Cult: Wyrmblade list

**To Reproduce**
1. Generate a Wyrmblade roster
2. Add an operative to the roster
3. Having selected the operative in the centre window, no equipment options are presented on the right hand side.

**Expected behavior**
A list of equipment options to be presented.  

**Screenshots**
n/a

**Device and data (please complete the following information):**
 - Windows Desktop
 - BattleScribe version v2.03.21.166
 - Release version Warhammer 40,000 Kill Team v3.0.15

**Additional context**
There is a list available here HOWEVER I do not have access to the source material, so I'm assuming the details on this site are accurate:
https://wahapedia.ru/kill-team2/kill-teams/wyrmblade/#Equipment

Big thank you to everyone who builds and maintains these lists - you're all bloody brilliant

**Comment by Mad-Spy** [comment]
You don't add equipment to Rosters, you only add it to Kill Teams. Select a Kill Team type Force when building your list.
