### ISSUE TITLE
[Anon] Bug report: 2021 - Void-Dancer Troupe.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#742]
**File:** 2021 - Void-Dancer Troupe.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** When you make a roster and you surpass the number of 18 operatives, you get this message: "Too many selections from Operative (maximum 18)". The maximum number of operatives in a roster is 20.

**Comment by Mad-Spy** [comment]
Sounds like you've got 19 operatives _and_ two Leaders. They're counted separately and adding a leader reduces the number of "operatives" available to your Roster.
