### ISSUE TITLE
[Anon] Bug report: 2021 - Death Guard.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#743]
**File:** 2021 - Death Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** It is possible to include three death guard operatives in fire team while compendium states you can include only two operative and leader if there is no other leader in kill team.

**Comment by Mad-Spy** [comment]
The Balance Dataslate changed the team composition.
