### ISSUE TITLE
Assault Intercessors allow too many Warriors

### ISSUE THREAD

**Issue by CpleChuck** [BSData/wh40k-killteam#748]
**Describe the bug**
Assault Intercessors allow 5 Warriors instead of 4.

**To Reproduce**

1. Open Battlescribe (2.03.21)
2. Create Kill Team (2021) Assault Intercessor Fire Team
3. Add 5 Warriors (valid)

**Expected behavior**

Only 4 Warriors allowed

**Screenshots**

![grafik](https://user-images.githubusercontent.com/105563020/168444799-15587dc9-787f-40ed-9c39-5fa694c0806a.png)
![grafik](https://user-images.githubusercontent.com/105563020/168444791-7ab65b4b-4b7d-4f0f-92ed-07238f3bc04f.png)

**Device and data (please complete the following information):**
 - PC Win10
 - BattleScribe version 2.03.21
 - Kill Team (2021) v3

**Comment by Mad-Spy** [comment]
The rules were changed in the Balance Dataslate 2022. https://www.warhammer-community.com/wp-content/uploads/2022/03/NoRqWNpHoXuqIbg8.pdf
