### ISSUE TITLE
[Anon] Bug report: 2021 - Void-Dancer Troupe.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#749]
**File:** 2021 - Void-Dancer Troupe.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The equipment available to the Void-Dancer Troupe isn't available for me to select because it does not show up at all when building my Kill Team.

**Comment by Mad-Spy** [comment]
You need to choose to build a Kill Team when selecting the Force type, rather than a Roster. As per the rules, you only select Equipment after selecting a kill team from your Roster.
