### ISSUE TITLE
False Error

### ISSUE THREAD

**Issue by Podman46** [BSData/wh40k-killteam#804]
**Describe the bug**
The validator tells me my roster size is to big when its not.

**To Reproduce**
I created a new Warhammer 40,000: Kill Team v3.8.4 Roster
I then select Kasrkin Roster Warhammer 40,000: Kill Team (2021) v6
I then add force Kasrkin v2 Roster and Kasrkin Kill Team

**Expected behavior**
I create the playing Kill team in the Kasrkin Kill Team section and shows no errors.
I then go to the roster and create my available Roster which is allowed up to 20 options.
However Even though my roster only has 16 options listed in it tells me I have 5 to many options
selected from operative. (maximum 17)

Its counting the selections in the Kill Team section towards my total. If I create just the roster its fine,
and if I create just the Kill team its fine. but if I create both it causes the issue. If i delete the 5 selections
from either the roster and or kill team it removes the error.

**Screenshots**
I included a Screen shot

**Device and data (please complete the following information):**
BattleScribe v2.03.21.166

**Additional context**
On a side note the equipment is missing the combat Knife from the new balance data slate.

![2023-04-01](https://user-images.githubusercontent.com/129574906/229266914-f2cf89dc-4b5b-46b0-b1c1-82b7412ff96f.png)

**Comment by Mad-Spy** [comment]
Not a false error. The validation is not designed to run a Roster force type and a Kill Team force type in the same Battlescribe Roster file.

**Comment by Podman46** [comment]
I assumed it was since it lists both types and allowed both to be selected. I'm new to using it.
