### ISSUE TITLE
[Anon] Bug report: 2021 - Imperial Navy Breacher.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#811]
**File:** 2021 - Imperial Navy Breacher.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I can’t select equipment for this team. There are none to choose from.

**Comment by Mad-Spy** [comment]
In order to select equipment, you must choose the "Kill Team" force type.
