### ISSUE TITLE
Hierotek Circle: WS/BS some Operatives and Leaders are wrong

### ISSUE THREAD

**Issue by TheSuperKonsti** [BSData/wh40k-killteam#815]
**Describe the bug**

The WS/BS of the Immortal Despotek and Apprentek are wrong, and the WS of the Crypteks are wrong. 
The Crypteks and the Apprentek should alle have 3+ WS/BS.
The Immortal Despotek should have 2+ WS/BS.

**Comment by Mad-Spy** [comment]
Fixed in #812
