### ISSUE TITLE
Include strategic and tactical ploys in the output

### ISSUE THREAD

**Issue by minimeee** [BSData/wh40k-killteam#821]
**Is your feature request related to a problem? Please describe.**
I created two killteams (Veteran Guardsmen and Hunter Cadre). While it's possible to add references for e. g. guardsmen orders, I can't find how to add strategic and tactical ploys to any of those team.

**Describe the solution you'd like**
I'd like to be able to add strategic and tactical ploys for every team.

**Describe alternatives you've considered**
Interestingly enough, when converting my roster using [dataslate.rocks](https://dataslate.rocks/), it adds both strategical and tactical ploys to the output. I'm not sure if that information is extracted from the roster or from some external source, but it would be very nice to also have it in the BattleScribe native output.

**Comment by Mad-Spy** [comment]
They are quite deliberately not there.
