### ISSUE TITLE
Balance Dataslate Q2 2023 - Chaos Cult

### ISSUE THREAD

**Issue by kurgol** [BSData/wh40k-killteam#841]
**Describe the bug**

Updates from the [Balance Dataslate Q2 2023](https://www.warhammer-community.com/wp-content/uploads/2023/03/qUKnZJIxrmhpWMfk.pdf)

## CHAOS CULT
* seem to be missing entirely, but changes from the published rules below
* ICONARCH’s Ruinous Invigoration ability: To a minimum of 3 (instead of 2).

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: MacOS Ventura 13.5
 - App being used to create lists: Battlescribe
 - App version: 2.03.21
 - Data release version: 3.9.0

**Additional context**

**Comment by Mad-Spy** [comment]
Not yet implemented, so will be implemented including these changes when they get done.
