### ISSUE TITLE
Add Inquisition Kill Team

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k-killteam#845]
### New stuff

- [x] Add Inquisition operatives
- [x] Add Sisters of Silence operatives
- [x] Add Tempestus Scions
- [x] Add Equipment
- [x] Add Battle Honours

### Operatives from other teams

- [x] Exaction Squad
- [x] Imperial Navy Breachers
- [x] Kasrkin
- [x] Vet Guardsman

**Comment by Bagel210** [comment]
Could you push up the PR for this so others could potentially build on it? This has been open for a while and would be great to get this closed.

**Comment by Mad-Spy** [comment]
It's stalled because the implementation for the Kill Team data wasn't designed to have models pulled in from other catalogues, because that concept didn't exist prior to Inquisition.

Ideally, the 4 catalogues above would get rewritten to support their models being shared across to Inquisition. This makes things more easily maintainable in the future when the other catalogues have changes made (after a data-slate, for instance). However, this would break every existing list made with those 4 catalogues.

The other option is to copy everything into Inquisition, which then makes maintaining the data in the future more of a pain, and is non-trivial in itself.

Either way, it's several hours work per catalogue. 

@Bagel210, are you offering to do this work? Do you have any prior experience in working on BS data files?

There are currently only 2 of us supporting on this system, for free, in our spare time. If you're offering to help out, that's great.
Otherwise, it'll be finished when I have the time to spare to do the required work.

**Comment by Bagel210** [comment]
Ahh that makes sense! That’s really annoying and there isn’t a great solution to it as you say. 

I don’t have prior experience at this time but was looking to see if I can contribute to help out where I can - hence why I was looking to see if there was a pull request I could work try and work off.

**Comment by mal20k** [comment]
I've gotten around to working on this. Have the Breachers and Kasrkin with basic links on the branch so far.
