### ISSUE TITLE
Intercessors missing krak grenades

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#85]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Just wanted to inform you that on battlescribe intercessors are shown not having krak grenades but on pg 85 of the kill ream rule book their profile shows them as having it. Also says the same thing on Ipad

**Comment by amis92** [comment]
Checked: Gunner and Sergeant indeed lack Krak grenades.
