### ISSUE TITLE
App crash when creating roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#86]
**File:** Warhammer 40,000 Kill Team.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I create a roster using the kill team 2018 v4 game system, the app crashes when I click on the button to create the roster (after setting the name and the point limit)
iPhone 8 256Go

**Comment by FarseerVeraenthis** [comment]
This is not happening on Android. 
Which particular CAT were you trying to use, or was it all of them??

**Comment by OftKilted** [comment]
Unable to replicate crashing on IOS v11.4.1
