### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Michael-Voss** [BSData/wh40k-killteam#861]
### Your Discord

michael_voss

### Additional information

Hi,
I am a software developer and 40k enthusiast. I started Killteam a year ago, but lacking enough people in my direct vicinity to play it, I started searching for online alternatives and found this repository.

And since i really like the hobby, I wanted to help, if I can :-)

**Comment by Mad-Spy** [comment]
Thanks for the offer, but there's not currently any need for any more regular help given the slow pace of KT releases. If there's enough need for more people at some point, well come back to you.
