### ISSUE TITLE
A couple of errors I've spotted

### ISSUE THREAD

**Issue by Aerobun** [BSData/wh40k-killteam#866]
I really hope I'm doing this the right way.

There is a numerical error with Blooded traitor gunner w/ grenade launcher: Damage value of Krak grenade profile should be 4/5.
Missing critical hit rule for Corsair gunner w/ shredder: rending.

I'm really sorry If I've reported this in a wrong way or if it's not helpful at all.
By the way, big thanks for upkeeping this database.

**Comment by mal20k** [comment]
You're definitely doing this the right way :) Thanks for pointing those out! Got a quick fix for them ready to go.

**Comment by Aerobun** [comment]
Glad I was able to help, thanks for your work.
