### ISSUE TITLE
Grey Knights specialists

### ISSUE THREAD

**Issue by BerkshireKnight** [BSData/wh40k-killteam#87]
Few issues with selecting specialists for Grey Knights (tested using the Campaign Command Roster):

- [x] Campaign Command Roster shouldn't impose maximum limits on Justicars and Grey Knight Gunners
- [x] Should be able to select Justicars as Specialists (i.e., give them Specialisms other than Leader)
- [x] Should be able to select Justicars as part of a Grey Knight Fire Team

**Comment by Mad-Spy** [comment]
I can see why this was left out initially. Adding multiple Justicars to a Kill Team is only possible in Open Play, as in all other Game Types, the single Justicar you are allowed in your Kill Team _must_ be the Leader.
