### ISSUE TITLE
Intercession Squad Methodical Chapter Tactic using pre-2023 Q2 Dataslate text

### ISSUE THREAD

**Issue by emuller42** [BSData/wh40k-killteam#872]
v8 release of the Intercession Squad rules shows the pre-dataslate versions of the Methodical Chapter Tactic for the selection under "Configuration".

The Methodical ability as added to operatives appears correct.

**Comment by mal20k** [comment]
I am not seeing this issue. Using Rapid as the example, the latest Intercession squad file on master has:

> While this operative is performing a Normal Move action, add ▲ to its Movement characteristic.

Which is the same as the one in the Intercession squad rule book that the latest balance dataslate points to.

This is true for the other chapter tactics as well.

**Comment by emuller42** [comment]
Updated, having dug further, it appears that there are two descriptions for each chapter tactic in the .cat, and the ones for the Methodical Chapter Tactic have diverged.
