### ISSUE TITLE
KT2018 Adeptus Astartes: Incorrect points cost for Adeptus Astartes Heavy Bolter 

### ISSUE THREAD

**Issue by Arvkon** [BSData/wh40k-killteam#876]
**Describe the bug**
The points cost listed for an Adeptus Astartes Heavy Bolter weapon in both the Core Manual and the Annual 2019 is 3pts.

The points cost for this weapon in BattleScribe is 6pts (see screenshots below).

**To Reproduce**
Two places to find the Heavy Bolter are in the Scout Gunner and Tactical Marine Gunner entries.

**Expected behavior**
The points cost should be 3pts instead of 6pts.

**Screenshots**
![IMG_0070 40p](https://github.com/BSData/wh40k-killteam/assets/7681406/6bf6da40-c537-42a6-a0c7-2e7a6cbd1da0)

![IMG_0069 40p](https://github.com/BSData/wh40k-killteam/assets/7681406/d5f04ebe-7050-405d-b553-6d7ec3a8c3e7)

**Device and data (please complete the following information):**
- iOS 17.3
- iPhone 12 mini
- BattleScribe app version 2.03.15

**Comment by Mad-Spy** [comment]
Pariah Nexus was the last update for the 2018 game system and the cost of a heavy bolter in that update is 6pts. The cost is correct.
