### ISSUE TITLE
[Anon] Bug report: 2021 - Nemesis Claw.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#881]
**File:** 2021 - Nemesis Claw.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Equipment (normal) not showing i.e. not able to select any. Can see a text box for equipment, but it seems to contain a heading only. May be user error - if so, apologies. Discord handle is Overwatch9463

**Comment by mal20k** [comment]
Not user error in this case! Looks like somehow I made a new Equipment section in each model instead of linking to the actual one containing all the equipment.
