### ISSUE TITLE
[Anon] Bug report: 2021 - Inquisitorial Agents.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#890]
**File:** 2021 - Inquisitorial Agents.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** Yes

**Description:** - Interrogator and Tome-Skull GA should be 2.
- "maximum of two AP2 weapons in entire team" restriction not triggering alert.

**Comment by mal20k** [comment]
The issues have been partially fixed, but I haven't pushed a release yet. There is a bug in NewRecruit where the marker for the AP2 weapons on the Navy Breachers Gunners is not being applied so while the check works in general it doesn't include the auxiliaries.

Leaving this open as a reminder to check about the issue and make a release with this fix later.

**Comment by mal20k** [comment]
Fixed, it was me being dumb when checking the solution.
