### ISSUE TITLE
Imperial Agents errors

### ISSUE THREAD

**Issue by FishQueen1702** [BSData/wh40k-killteam#893]
- The Mystic unit should be able to equip the MC Autopistol equipment and can't.

- the Death World Veteran's polearm has the reap 2 special rule but it doesn't show that rule at the bottom of the page
![image](https://github.com/user-attachments/assets/88fba8e2-3a3c-4a6e-9b8d-118d787a58a2)

**Comment by mal20k** [comment]
Forgot to put in the commit message, but fixed in: https://github.com/BSData/wh40k-killteam/commit/d3cfa3a89d155289f70033b71f321553bf2e2985
