### ISSUE TITLE
[Anon] Imperial Navy Breachers: For Imperial Navy Breachers in Kill Team 2024, CAT unit and Gheistskull should not count as extra operatives when paired with their operators.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-killteam#911]
**Problem:**
For Imperial Navy Breachers in Kill Team 2024, CAT unit and Gheistskull should not count as extra operatives when paired with their operators.

**Expected:**
I should be able to add the CAT unit and Gheistskull and have them not count as extra operatives when their operators are also in my selection. The pair of each operator and their device unit should count as one operative.

**List:** https://www.newrecruit.eu/app/list/zjBEL

**Comment by mal20k** [comment]
This list is working as intended. The CAT and Gheistskull count as half a selection each, meaning the number of physical models is 11 which is what the operative limit in the data represents. CAT + Surveyor/Gheiskull + Void-jammer do not count as 1 model, they count as 1.5 models which the data correctly restricts. That list is invalid as it includes 11/10 operatives from the rules perspective (10 regular selections plus two half selections).
