### ISSUE TITLE
[Anon] Warpcoven: It wont let me select a leader from the Sorcerers. Says i can only have 0 leaders

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-killteam#915]
**Problem:**
It wont let me select a leader from the sorcerer's. Says i can only have 0 leaders

**Expected:**
It to allow me to have the reccomended number of leaders, 1

 **Additional Info:**
Kill team warp coven pdf

**List:** https://www.newrecruit.eu/app/list/rDuE4
**Unit:** Sorcerer of Destiny, id: 9429-7bf0-c5e2-2535

**Comment by mal20k** [comment]
Sorcerers have a leader Selection. Choose a Sorcerer and then mark them as leader.

**Comment by mal20k** [comment]
![Screenshot_2024-12-15-00-23-01-00_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/0f57b9f7-4b65-440a-b5b7-1dff6fb81775)

**Comment by mal20k** [comment]
Double checked the list as well, it is a Roster, not the main team. The 0 max leaders is odd on a Roster so will look into that but the expectation in this issue is not a problem.
