### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Damian-R-Smith** [BSData/wh40k-killteam#919]
### Your Discord

javawocky875

### Additional information

Want to be involved as contributor for a few game systems, starting on some quieter repos to familarise myself with the BSData project fully. I am an active killteam player so would be very familiar with the rules and team data, and would be following any updates or changes to the game by GW.

I have already gone over the contribuiting guidlines and looked through the repo so I'm ready to jump straight in to help with the following:
  
- Follow any GW updates or balance changes to ensure data files are updated to reflect these changes.
- Track and resolve any issues or features assigned to me.
- Sumbit and review PR's.
- Maintain or add any documentation needed.

**Comment by mal20k** [comment]
No updates recently but we've got things handled. If you want to contribute then the best way is to submit bug reports here or via New Recruit's form, or if you find any issues sibmit a PR. Primary disvussion happens on the BSData Discord so make sure you join that if you have any questions.
