### ISSUE TITLE
Incorrect points, Conditions for Tau DS-8 Support Turret Wargear Option

### ISSUE THREAD

**Issue by CynicalCode** [BSData/wh40k-killteam#92]
Rulebook p.171 describes DS-8 turret as a wargear, listing two weapon options:
- Smart Missile System
- Missile Pod

It is restricted to Shas'la and one per killteam.

In addition, the DS-8 support turrent costs 0 points (Rulebook, pg.173), not 5 as indicated in the data files.

**Comment by amis92** [comment]
It is a *model* per points sheet on p173, and it's cost of 0 pts does not include wargear as indicated in the table. Thus the cost of the turret is 0 + cost of the weapon (5 for SMS, 7 for MP).

It has both those weapon options available. Restrictions are also enforced if your List Configuration is for Matched/Campaign Kill Team.
