### ISSUE TITLE
[Anon] Scout Squad: number of operatives

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-killteam#923]
**Problem:**
number of operatives

**Expected:**
9 operatives

 **Additional Info:**
it only allows 8

**List:** https://www.newrecruit.eu/app/list/1qwNk

**Comment by mal20k** [comment]
8 "normal" operatives and 1 leader, which this list has and the team doc as of posting this comment agrees with.
https://www.warhammer-community.com/en-gb/downloads/kill-team/
