### ISSUE TITLE
[Anon] Ratling: Missing Bullgryns

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-killteam#924]
**Problem:**
Missing Bullgryns

**Expected:**
Be able to select Bullgryn as described in the Brutal an Cunning box

**List:** https://www.newrecruit.eu/app/list/VGSW3
**Unit:** Ogryn[1], id: 4321-c089-f210-4f34

**Comment by mal20k** [comment]
Had fixed, forgot to release!

**Comment by NajeraVictor** [comment]
Unsubscribe
