### ISSUE TITLE
[Anon] Necrons: The cryptek models don't have their abilities

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/wh40k-killteam#925]
**Problem:**
The cryptek models don't have their abilities

**Expected:**
The Cryptek models should each have at least one ability, like the plasmancer having Harbinger of Despair. These are missing

**List:** https://www.newrecruit.eu/app/list/vVDf7

**Comment by Samclaus123** [comment]
Those are tactics not abilities

**Comment by Mad-Spy** [comment]
1. There is no Plasmancer model in the Hierotech Circle Kill Team. I assume you mean Psychomancer.
2. All the models have their Unique Actions (not abilities or tactics) implemented correctly. I can only assume that you haven't expanded the dropdown which contains them.
