### ISSUE TITLE
Tau: One carbine for MV1 Gun Drone in minimal output

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#93]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** MV1 gun drones has 2 pulse carbines, when I print out or preview it is only one carbine seen. Everytime I have to show rulebook to mu opponent. In statements it has to ve written "model is equipped with two pulse carbines". Thanks

**Comment by amis92** [comment]
You're probably using minimal output, which means only **profile** of the weapon is printed, not who and how many of it has.

Please, in output settings change output to full.
