### ISSUE TITLE
Fire Warrior Breacher Shas’ui Pistol

### ISSUE THREAD

**Issue by Icenor** [BSData/wh40k-killteam#95]
A Fire Warrior Breacher Shas’ui may take a Pulse Pistol and replace his Pulse Blaster for a second (I assume) Pulse Pistol, but I’m not able to do that in version 1.0.5.

**Comment by GenWilhelm** [comment]
He may take a Pulse Pistol, or he may **instead** replace his Pulse Blaster with a Pulse Pistol. It's one option or the other, but not both.

**Comment by Icenor** [comment]
That doesn’t make sense. All Breachers are armed with a Pulse Blaster and Photon Granade. All Breachers may take a Pulse Pistol. Why would you then replace your Pulse Blaster for a Pulse Pistol unless it was to dual wield pistols?

**Comment by GenWilhelm** [comment]
Again, you seem to be glossing over the word 'instead' in that second wargear option - if he could do both, it wouldn't be there; it would simply say 
- A Breacher Shas’ui may replace its pulse blaster with a pulse pistol.
