### ISSUE TITLE
Genestealer Cults: Acolyte Fighter Cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-killteam#96]
**File:** Genestealer Cults.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Acolyte fighter costs 1 more point than in the book. (9 instead of 8)

**Comment by GenWilhelm** [comment]
I can't reproduce this error on any platform.

Please can you ensure your data is up to date and, if the problem continues, provide more details on how or why the error occurs.
